// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class CalcResult
{
    public int CalcResultId { get; set; }

    public string CalculationId { get; set; }

    public string CalculationName { get; set; }

    public string Value { get; set; }

    public string ExceptionType { get; set; }

    public string ExceptionMessage { get; set; }

    public string ExceptionStackTrace { get; set; }

    public string CalculationType { get; set; }

    public string CalculationDataType { get; set; }

    public string ProviderResultId { get; set; }

    public virtual Calculation Calculation { get; set; }

    public virtual ProviderResult ProviderResult { get; set; }
}