// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class Calculation
{
    public string CalculationId { get; set; }

    public string SpecificationId { get; set; }

    public int FundingStreamId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<CalcResult> CalcResults { get; set; } = new List<CalcResult>();

    public virtual ICollection<CalculationVersion> CalculationVersions { get; set; } = new List<CalculationVersion>();

    public virtual FundingStream FundingStream { get; set; }

    public virtual ICollection<ObsoleteItemCalc> ObsoleteItemCalcs { get; set; } = new List<ObsoleteItemCalc>();

    public virtual Specification Specification { get; set; }
}