// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class CalculationVersion
{
    public string CalculationVersionId { get; set; }

    public string CalculationId { get; set; }

    public string SourceCode { get; set; }

    public string CalculationType { get; set; }

    public string SourceCodeName { get; set; }

    public string Name { get; set; }

    public string Namespace { get; set; }

    public bool WasTemplateCalculation { get; set; }

    public string ValueType { get; set; }

    public string Description { get; set; }

    public string DataType { get; set; }

    public string AllowedTypeValues { get; set; }

    public int Version { get; set; }

    public DateTime Date { get; set; }

    public string AuthorId { get; set; }

    public string AuthorName { get; set; }

    public string Comment { get; set; }

    public string PublishStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsLatest { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Calculation Calculation { get; set; }
}