// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class CfsDbContext : DbContext
{
    public CfsDbContext(DbContextOptions<CfsDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CalcResult> CalcResults { get; set; }

    public virtual DbSet<Calculation> Calculations { get; set; }

    public virtual DbSet<CalculationVersion> CalculationVersions { get; set; }

    public virtual DbSet<ConverterDataMergeLog> ConverterDataMergeLogs { get; set; }

    public virtual DbSet<CurrentProviderVersion> CurrentProviderVersions { get; set; }

    public virtual DbSet<Dataset> Datasets { get; set; }

    public virtual DbSet<DatasetAggregation> DatasetAggregations { get; set; }

    public virtual DbSet<DatasetAggregationField> DatasetAggregationFields { get; set; }

    public virtual DbSet<DatasetDefinition> DatasetDefinitions { get; set; }

    public virtual DbSet<DatasetSpecificationRelationship> DatasetSpecificationRelationships { get; set; }

    public virtual DbSet<DatasetVersion> DatasetVersions { get; set; }

    public virtual DbSet<DefinitionSpecificationRelationship> DefinitionSpecificationRelationships { get; set; }

    public virtual DbSet<FundingLineResult> FundingLineResults { get; set; }

    public virtual DbSet<FundingPeriod> FundingPeriods { get; set; }

    public virtual DbSet<FundingStream> FundingStreams { get; set; }

    public virtual DbSet<FundingStreamPeriodProfilePattern> FundingStreamPeriodProfilePatterns { get; set; }

    public virtual DbSet<ObsoleteItem> ObsoleteItems { get; set; }

    public virtual DbSet<ObsoleteItemCalc> ObsoleteItemCalcs { get; set; }

    public virtual DbSet<Policy> Policies { get; set; }

    public virtual DbSet<Predecessor> Predecessors { get; set; }

    public virtual DbSet<ProfilePatternPeriod> ProfilePatternPeriods { get; set; }

    public virtual DbSet<Provider> Providers { get; set; }

    public virtual DbSet<ProviderResult> ProviderResults { get; set; }

    public virtual DbSet<ProviderSourceDataset> ProviderSourceDatasets { get; set; }

    public virtual DbSet<ProviderSourceDatasetVersion> ProviderSourceDatasetVersions { get; set; }

    public virtual DbSet<ProviderSpecificationResult> ProviderSpecificationResults { get; set; }

    public virtual DbSet<ProviderTypeSubType> ProviderTypeSubTypes { get; set; }

    public virtual DbSet<ProviderVersionFundingPeriodDetail> ProviderVersionFundingPeriodDetails { get; set; }

    public virtual DbSet<ProviderVersionMetadatum> ProviderVersionMetadata { get; set; }

    public virtual DbSet<ReProfilingConfigurationProperty> ReProfilingConfigurationProperties { get; set; }

    public virtual DbSet<Specification> Specifications { get; set; }

    public virtual DbSet<SpecificationVersion> SpecificationVersions { get; set; }

    public virtual DbSet<Successor> Successors { get; set; }

    public virtual DbSet<Template> Templates { get; set; }

    public virtual DbSet<TemplateMapping> TemplateMappings { get; set; }

    public virtual DbSet<TemplateMappingItem> TemplateMappingItems { get; set; }

    public virtual DbSet<TemplatePredecessor> TemplatePredecessors { get; set; }

    public virtual DbSet<TemplateVersion> TemplateVersions { get; set; }

    public virtual DbSet<VariationPointer> VariationPointers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CalcResult>(entity =>
        {
            entity.ToTable("CalcResults", "dbo");

            entity.HasIndex(e => new { e.CalculationId, e.ProviderResultId }, "IX_CalcResults_Calc_Provider");

            entity.HasIndex(e => e.ProviderResultId, "IX_CalcResults_ProviderResult");

            entity.Property(e => e.CalculationDataType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CalculationId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CalculationName)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.CalculationType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ExceptionType).HasMaxLength(50);
            entity.Property(e => e.ProviderResultId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Value).HasMaxLength(50);

            entity.HasOne(d => d.Calculation).WithMany(p => p.CalcResults)
                .HasForeignKey(d => d.CalculationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CalcResults_CalculationId");

            entity.HasOne(d => d.ProviderResult).WithMany(p => p.CalcResults)
                .HasForeignKey(d => d.ProviderResultId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CalcResults_ProviderResult");
        });

        modelBuilder.Entity<Calculation>(entity =>
        {
            entity.ToTable("Calculations", "dbo");

            entity.Property(e => e.CalculationId).HasMaxLength(255);
            entity.Property(e => e.SpecificationId)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);

            entity.HasOne(d => d.FundingStream).WithMany(p => p.Calculations)
                .HasForeignKey(d => d.FundingStreamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Calculations_FundingStreams");

            entity.HasOne(d => d.Specification).WithMany(p => p.Calculations)
                .HasForeignKey(d => d.SpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Calculations_Specifications");
        });

        modelBuilder.Entity<CalculationVersion>(entity =>
        {
            entity.ToTable("CalculationVersions", "dbo");

            entity.HasIndex(e => new { e.CalculationId, e.IsLatest, e.IsDeleted }, "IX_CalculationVersions_CalculationId_IsLatest_IsDeleted");

            entity.Property(e => e.CalculationVersionId).HasMaxLength(255);
            entity.Property(e => e.AuthorId)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.AuthorName)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.CalculationId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CalculationType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DataType).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.Namespace)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PublishStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SourceCode).IsRequired();
            entity.Property(e => e.SourceCodeName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ValueType)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Calculation).WithMany(p => p.CalculationVersions)
                .HasForeignKey(d => d.CalculationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CalculationVersions_Calculations");
        });

        modelBuilder.Entity<ConverterDataMergeLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Id");

            entity.ToTable("ConverterDataMergeLogs", "dbo");

            entity.HasIndex(e => e.ParentJobId, "ConverterDataMergeLogs_ParentJobId");

            entity.Property(e => e.Id).HasMaxLength(255);
            entity.Property(e => e.ContentJson).IsRequired();
            entity.Property(e => e.ParentJobId).HasMaxLength(255);
        });

        modelBuilder.Entity<CurrentProviderVersion>(entity =>
        {
            entity.ToTable("CurrentProviderVersion", "dbo");

            entity.Property(e => e.CurrentProviderVersionId).HasMaxLength(50);
            entity.Property(e => e.ProviderVersionId)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Dataset>(entity =>
        {
            entity.HasKey(e => e.DatasetId).HasName("PK_DatasetId");

            entity.ToTable("Datasets", "dbo");

            entity.Property(e => e.DatasetId).HasMaxLength(255);
            entity.Property(e => e.DatasetSpecificationRelationshipId).HasMaxLength(255);
            entity.Property(e => e.DefinitionId).HasMaxLength(255);
            entity.Property(e => e.DefinitionName).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(255);
        });

        modelBuilder.Entity<DatasetAggregation>(entity =>
        {
            entity.ToTable("DatasetAggregations", "dbo");

            entity.Property(e => e.DatasetAggregationId).HasMaxLength(512);
            entity.Property(e => e.DatasetRelationshipId)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.SpecificationId)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);

            entity.HasOne(d => d.Specification).WithMany(p => p.DatasetAggregations)
                .HasForeignKey(d => d.SpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DatasetsAggregations_SpecificationId");
        });

        modelBuilder.Entity<DatasetAggregationField>(entity =>
        {
            entity.ToTable("DatasetAggregationFields", "dbo");

            entity.Property(e => e.DatasetAggregationId)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.FieldDefinitionName)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.FieldType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Value).HasColumnType("decimal(30, 12)");

            entity.HasOne(d => d.DatasetAggregation).WithMany(p => p.DatasetAggregationFields)
                .HasForeignKey(d => d.DatasetAggregationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DatasetAggregationField_DatasetAggregations");
        });

        modelBuilder.Entity<DatasetDefinition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_DatasetDefinitionId");

            entity.ToTable("DatasetDefinitions", "dbo");

            entity.Property(e => e.Id).HasMaxLength(64);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.TableDefinitions).IsRequired();
            entity.Property(e => e.ValidateProvidersByYearRange).HasDefaultValue(0);

            entity.HasOne(d => d.FundingStream).WithMany(p => p.DatasetDefinitions)
                .HasForeignKey(d => d.FundingStreamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DatasetDefinitions_FundingStreams");
        });

        modelBuilder.Entity<DatasetSpecificationRelationship>(entity =>
        {
            entity.HasKey(e => e.DatasetSpecificationRelationshipVersionId).HasName("PK_DatasetSpecificationRelationshipVersionId");

            entity.ToTable("DatasetSpecificationRelationships", "dbo");

            entity.Property(e => e.DatasetSpecificationRelationshipVersionId).HasMaxLength(255);
            entity.Property(e => e.AuthorId).HasMaxLength(256);
            entity.Property(e => e.AuthorName).HasMaxLength(256);
            entity.Property(e => e.DatasetDefinitionId).HasMaxLength(255);
            entity.Property(e => e.DatasetDefinitionName).HasMaxLength(255);
            entity.Property(e => e.DatasetId).HasMaxLength(255);
            entity.Property(e => e.DatasetSpecificationRelationshipId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.FundingPeriodName).HasMaxLength(128);
            entity.Property(e => e.LastUpdated).HasColumnName("lastUpdated");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PublishStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PublishedSpecificationId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.RelationshipType)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.SpecificationId)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);

            entity.HasOne(d => d.Specification).WithMany(p => p.DatasetSpecificationRelationships)
                .HasForeignKey(d => d.SpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DatasetSpecificationRelationships_Specifications");
        });

        modelBuilder.Entity<DatasetVersion>(entity =>
        {
            entity.HasKey(e => e.DatasetVersionId).HasName("PK_DatasetVersionId");

            entity.ToTable("DatasetVersions", "dbo");

            entity.Property(e => e.DatasetVersionId).HasMaxLength(255);
            entity.Property(e => e.AuthorId).HasMaxLength(256);
            entity.Property(e => e.AuthorName).HasMaxLength(256);
            entity.Property(e => e.BlobName)
                .IsRequired()
                .HasMaxLength(1024);
            entity.Property(e => e.ChangeType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DatasetId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ProviderVersionId).HasMaxLength(50);
            entity.Property(e => e.PublishStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UploadedBlobFilePath).HasMaxLength(1024);

            entity.HasOne(d => d.Dataset).WithMany(p => p.DatasetVersions)
                .HasForeignKey(d => d.DatasetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DatasetVersion_Datasets");

            entity.HasOne(d => d.FundingStream).WithMany(p => p.DatasetVersions)
                .HasForeignKey(d => d.FundingStreamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DatasetVersions_FundingStreams");
        });

        modelBuilder.Entity<DefinitionSpecificationRelationship>(entity =>
        {
            entity.ToTable("DefinitionSpecificationRelationships", "dbo");

            entity.Property(e => e.DataDefinitionRelationshipId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.SpecificationVersionId)
                .IsRequired()
                .HasMaxLength(512)
                .IsUnicode(false);

            entity.HasOne(d => d.SpecificationVersion).WithMany(p => p.DefinitionSpecificationRelationships)
                .HasForeignKey(d => d.SpecificationVersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DefinitionSpecificationRelationships_SpecificationVersions");
        });

        modelBuilder.Entity<FundingLineResult>(entity =>
        {
            entity.ToTable("FundingLineResults", "dbo");

            entity.HasIndex(e => new { e.FundingLineId, e.ProviderResultId }, "IX_FundingLineResults_FundingLine_Provider");

            entity.HasIndex(e => e.ProviderResultId, "IX_FundingLineResults_ProviderResult");

            entity.Property(e => e.ExceptionType).HasMaxLength(50);
            entity.Property(e => e.FundingLineFundingStreamId)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FundingLineId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FundingLineName).IsRequired();
            entity.Property(e => e.ProviderResultId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Value).HasMaxLength(50);

            entity.HasOne(d => d.ProviderResult).WithMany(p => p.FundingLineResults)
                .HasForeignKey(d => d.ProviderResultId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FundingLineResults_ProviderResult");
        });

        modelBuilder.Entity<FundingPeriod>(entity =>
        {
            entity.ToTable("FundingPeriods", "dbo");

            entity.HasIndex(e => e.FundingPeriodCode, "IX_FundingPeriods_FundingPeriodCode").IsUnique();

            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.FundingPeriodCode)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.FundingPeriodName)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.Period)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Type)
                .HasMaxLength(64)
                .IsUnicode(false);
        });

        modelBuilder.Entity<FundingStream>(entity =>
        {
            entity.HasKey(e => e.FundingStreamId).HasName("PK_FundingStreamId");

            entity.ToTable("FundingStreams", "dbo");

            entity.HasIndex(e => e.FundingStreamCode, "IX_FundingStreams_FundingStreamCode").IsUnique();

            entity.Property(e => e.FundingStreamCode)
                .IsRequired()
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.FundingStreamName)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.ShortFundingStreamName).HasMaxLength(256);
        });

        modelBuilder.Entity<FundingStreamPeriodProfilePattern>(entity =>
        {
            entity.ToTable("FundingStreamPeriodProfilePatterns", "dbo");

            entity.HasIndex(e => new { e.FundingStreamId, e.FundingPeriodId, e.FundingLineId }, "IX_FundingStreamPeriodProfilePatterns_FundingStreamId_FundingPeriodId_FundingLineId");

            entity.Property(e => e.Id).HasMaxLength(255);
            entity.Property(e => e.Etag)
                .HasMaxLength(255)
                .HasColumnName("ETag");
            entity.Property(e => e.FundingLineId)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ProfileCacheEtag)
                .HasMaxLength(255)
                .HasColumnName("ProfileCacheETag");
            entity.Property(e => e.ProfilePatternDescription).HasMaxLength(255);
            entity.Property(e => e.ProfilePatternDisplayName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ProfilePatternKey).HasMaxLength(100);
            entity.Property(e => e.ProfilePatternType).HasMaxLength(100);
            entity.Property(e => e.RoundingStrategy)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.FundingPeriod).WithMany(p => p.FundingStreamPeriodProfilePatterns)
                .HasForeignKey(d => d.FundingPeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FundingStreamPeriodProfilePatterns_FundingPeriods");

            entity.HasOne(d => d.FundingStream).WithMany(p => p.FundingStreamPeriodProfilePatterns)
                .HasForeignKey(d => d.FundingStreamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FundingStreamPeriodProfilePatterns_FundingStreams");
        });

        modelBuilder.Entity<ObsoleteItem>(entity =>
        {
            entity.HasKey(e => e.ObsoleteItemId).HasName("PK_ObsoleteItem");

            entity.ToTable("ObsoleteItems", "dbo");

            entity.Property(e => e.ObsoleteItemId).HasMaxLength(255);
            entity.Property(e => e.CodeReference)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.DatasetDataType).HasMaxLength(50);
            entity.Property(e => e.DatasetFieldId).HasMaxLength(50);
            entity.Property(e => e.DatasetFieldName).HasMaxLength(50);
            entity.Property(e => e.DatasetRelationshipId).HasMaxLength(255);
            entity.Property(e => e.DatasetRelationshipName).HasMaxLength(50);
            entity.Property(e => e.EnumValueName).HasMaxLength(50);
            entity.Property(e => e.FundingLineName).HasMaxLength(50);
            entity.Property(e => e.ItemType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RelationshipName).HasMaxLength(255);
            entity.Property(e => e.SpecificationId)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);

            entity.HasOne(d => d.FundingStream).WithMany(p => p.ObsoleteItems)
                .HasForeignKey(d => d.FundingStreamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ObsoleteItem_FundingStreams");

            entity.HasOne(d => d.Specification).WithMany(p => p.ObsoleteItems)
                .HasForeignKey(d => d.SpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ObsoleteItem_Specifications");
        });

        modelBuilder.Entity<ObsoleteItemCalc>(entity =>
        {
            entity.ToTable("ObsoleteItemCalcs", "dbo");

            entity.Property(e => e.CalculationId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ObsoleteItemId)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Calculation).WithMany(p => p.ObsoleteItemCalcs)
                .HasForeignKey(d => d.CalculationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ObsoleteItemCalcs_Calculations");

            entity.HasOne(d => d.ObsoleteItem).WithMany(p => p.ObsoleteItemCalcs)
                .HasForeignKey(d => d.ObsoleteItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ObsoleteItemCalcs_ObsoleteItems");
        });

        modelBuilder.Entity<Policy>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Policies__3214EC070926B8AF");

            entity.ToTable("Policies", "dbo");

            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.DocumentType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PolicyId)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Predecessor>(entity =>
        {
            entity.ToTable("Predecessors", "dbo");

            entity.Property(e => e.ProviderId)
                .IsRequired()
                .HasMaxLength(16);
            entity.Property(e => e.ProviderVersionId)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.Ukprn)
                .IsRequired()
                .HasMaxLength(16)
                .HasDefaultValue("")
                .HasColumnName("UKPRN");

            entity.HasOne(d => d.Provider).WithMany(p => p.Predecessors)
                .HasPrincipalKey(p => new { p.ProviderId, p.ProviderVersionId })
                .HasForeignKey(d => new { d.ProviderId, d.ProviderVersionId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Predecessors_ToProvider");
        });

        modelBuilder.Entity<ProfilePatternPeriod>(entity =>
        {
            entity.ToTable("ProfilePatternPeriods", "dbo");

            entity.HasIndex(e => e.FundingStreamPeriodProfilePatternId, "IX_ProfilePatternPeriods_FundingStreamPeriodProfilePatternId");

            entity.Property(e => e.DistributionPeriod)
                .IsRequired()
                .HasMaxLength(16);
            entity.Property(e => e.FundingStreamPeriodProfilePatternId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Period)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PeriodPatternPercentage).HasMaxLength(29);
            entity.Property(e => e.PeriodType)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.FundingStreamPeriodProfilePattern).WithMany(p => p.ProfilePatternPeriods)
                .HasForeignKey(d => d.FundingStreamPeriodProfilePatternId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProfilePatternPeriods_FundingStreamPeriodProfilePatterns");
        });

        modelBuilder.Entity<Provider>(entity =>
        {
            entity.ToTable("Providers", "dbo");

            entity.HasIndex(e => e.Ukprn, "IX_Providers_UKPRN");

            entity.HasIndex(e => new { e.ProviderId, e.ProviderVersionId }, "UQ_Providers_ProviderVersionId").IsUnique();

            entity.Property(e => e.Address3).HasMaxLength(256);
            entity.Property(e => e.Authority).HasMaxLength(128);
            entity.Property(e => e.CensusWardCode).HasMaxLength(16);
            entity.Property(e => e.CensusWardName).HasMaxLength(128);
            entity.Property(e => e.CompaniesHouseNumber).HasMaxLength(16);
            entity.Property(e => e.CountyCode).HasMaxLength(16);
            entity.Property(e => e.CountyName).HasMaxLength(128);
            entity.Property(e => e.CrmAccountId).HasMaxLength(16);
            entity.Property(e => e.DfeEstablishmentNumber).HasMaxLength(16);
            entity.Property(e => e.DistrictCode).HasMaxLength(16);
            entity.Property(e => e.DistrictName).HasMaxLength(128);
            entity.Property(e => e.EstablishmentNumber).HasMaxLength(16);
            entity.Property(e => e.FurtherEducationTypeCode).HasMaxLength(32);
            entity.Property(e => e.FurtherEducationTypeName).HasMaxLength(255);
            entity.Property(e => e.GovernmentOfficeRegionCode).HasMaxLength(16);
            entity.Property(e => e.GovernmentOfficeRegionName).HasMaxLength(128);
            entity.Property(e => e.GroupIdNumber).HasMaxLength(16);
            entity.Property(e => e.LaCode).HasMaxLength(16);
            entity.Property(e => e.LaOrg).HasMaxLength(16);
            entity.Property(e => e.LegalName).HasMaxLength(510);
            entity.Property(e => e.LocalGovernmentGroupTypeCode).HasMaxLength(16);
            entity.Property(e => e.LocalGovernmentGroupTypeName).HasMaxLength(128);
            entity.Property(e => e.Locality).HasMaxLength(256);
            entity.Property(e => e.LondonRegionCode).HasMaxLength(16);
            entity.Property(e => e.LondonRegionName).HasMaxLength(128);
            entity.Property(e => e.LowerSuperOutputAreaCode).HasMaxLength(16);
            entity.Property(e => e.LowerSuperOutputAreaName).HasMaxLength(128);
            entity.Property(e => e.MiddleSuperOutputAreaCode).HasMaxLength(16);
            entity.Property(e => e.MiddleSuperOutputAreaName).HasMaxLength(128);
            entity.Property(e => e.Name).HasMaxLength(510);
            entity.Property(e => e.NavVendorNo).HasMaxLength(16);
            entity.Property(e => e.OfficialSixthFormCode).HasMaxLength(10);
            entity.Property(e => e.OfficialSixthFormName).HasMaxLength(30);
            entity.Property(e => e.ParliamentaryConstituencyCode).HasMaxLength(16);
            entity.Property(e => e.ParliamentaryConstituencyName).HasMaxLength(128);
            entity.Property(e => e.PaymentOrganisationIdentifier).HasMaxLength(16);
            entity.Property(e => e.PaymentOrganisationName).HasMaxLength(256);
            entity.Property(e => e.PhaseOfEducationCode).HasMaxLength(10);
            entity.Property(e => e.Postcode).HasMaxLength(16);
            entity.Property(e => e.PreviousEstablishmentNumber).HasMaxLength(16);
            entity.Property(e => e.PreviousLaCode).HasMaxLength(8);
            entity.Property(e => e.PreviousLaName).HasMaxLength(40);
            entity.Property(e => e.ProviderId)
                .IsRequired()
                .HasMaxLength(16);
            entity.Property(e => e.ProviderProfileIdType).HasMaxLength(128);
            entity.Property(e => e.ProviderSubType).HasMaxLength(64);
            entity.Property(e => e.ProviderSubTypeCode).HasMaxLength(10);
            entity.Property(e => e.ProviderType).HasMaxLength(64);
            entity.Property(e => e.ProviderTypeCode).HasMaxLength(10);
            entity.Property(e => e.ProviderVersionId)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.ReasonEstablishmentClosed).HasMaxLength(128);
            entity.Property(e => e.ReasonEstablishmentClosedCode).HasMaxLength(10);
            entity.Property(e => e.ReasonEstablishmentOpened).HasMaxLength(128);
            entity.Property(e => e.ReasonEstablishmentOpenedCode).HasMaxLength(10);
            entity.Property(e => e.RscRegionCode).HasMaxLength(16);
            entity.Property(e => e.RscRegionName).HasMaxLength(128);
            entity.Property(e => e.Status).HasMaxLength(64);
            entity.Property(e => e.StatusCode).HasMaxLength(10);
            entity.Property(e => e.StatutoryHighAge).HasMaxLength(5);
            entity.Property(e => e.Street).HasMaxLength(510);
            entity.Property(e => e.Successor).HasMaxLength(128);
            entity.Property(e => e.Town).HasMaxLength(256);
            entity.Property(e => e.TrustCode).HasMaxLength(16);
            entity.Property(e => e.TrustName).HasMaxLength(510);
            entity.Property(e => e.TrustStatus).HasMaxLength(64);
            entity.Property(e => e.Ukprn).HasMaxLength(16);
            entity.Property(e => e.Upin).HasMaxLength(16);
            entity.Property(e => e.Urn).HasMaxLength(16);
            entity.Property(e => e.WardCode).HasMaxLength(16);
            entity.Property(e => e.WardName).HasMaxLength(128);
        });

        modelBuilder.Entity<ProviderResult>(entity =>
        {
            entity.HasKey(e => e.ProviderResultId).HasName("PK_ProviderResult");

            entity.ToTable("ProviderResults", "dbo");

            entity.HasIndex(e => new { e.SpecificationId, e.ProviderId, e.ProviderVersionId }, "IX_ProviderResult_Spec_Provider");

            entity.Property(e => e.ProviderResultId).HasMaxLength(255);
            entity.Property(e => e.ProviderId)
                .IsRequired()
                .HasMaxLength(16);
            entity.Property(e => e.ProviderVersionId)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.SpecificationId)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);

            entity.HasOne(d => d.Specification).WithMany(p => p.ProviderResults)
                .HasForeignKey(d => d.SpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProviderResult_Specification");

            entity.HasOne(d => d.Provider).WithMany(p => p.ProviderResults)
                .HasPrincipalKey(p => new { p.ProviderId, p.ProviderVersionId })
                .HasForeignKey(d => new { d.ProviderId, d.ProviderVersionId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProviderResult_Provider");
        });

        modelBuilder.Entity<ProviderSourceDataset>(entity =>
        {
            entity.HasKey(e => e.ProviderSourceDatasetId).HasName("PK_ProviderSourceDatasetId");

            entity.ToTable("ProviderSourceDatasets", "dbo");

            entity.HasIndex(e => new { e.SpecificationId, e.DatasetRelationshipSummaryId }, "IX_ProviderSourceDatasets_SpecificationId_DatasetRelationshipSummaryId");

            entity.Property(e => e.ProviderSourceDatasetId).HasMaxLength(255);
            entity.Property(e => e.DataDefinitionId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.DataGranularity)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.DataRelationshipSummaryName)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.DatasetRelationshipSummaryId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.DatasetRelationshipType).HasMaxLength(50);
            entity.Property(e => e.DefinesScope).HasDefaultValue(false);
            entity.Property(e => e.ProviderId)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.SpecificationId)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);

            entity.HasOne(d => d.Specification).WithMany(p => p.ProviderSourceDatasets)
                .HasForeignKey(d => d.SpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProviderSourceDatasets_Specifications");
        });

        modelBuilder.Entity<ProviderSourceDatasetVersion>(entity =>
        {
            entity.HasKey(e => e.ProviderSourceDatasetVersionId).HasName("PK_ProviderSourceDatasetVersionId");

            entity.ToTable("ProviderSourceDatasetVersions", "dbo");

            entity.HasIndex(e => new { e.ProviderSourceDatasetId, e.IsLatest, e.IsDeleted }, "IX_ProviderSourceDatasetVersions_ProviderSourceDatasetId_IsLatest_IsDeleted");

            entity.Property(e => e.ProviderSourceDatasetVersionId).HasMaxLength(255);
            entity.Property(e => e.AuthorId)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.AuthorName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Comment).HasMaxLength(255);
            entity.Property(e => e.DatasetId).HasMaxLength(255);
            entity.Property(e => e.DatasetName).HasMaxLength(255);
            entity.Property(e => e.ProviderSourceDatasetId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ProviderSourceDatasetRowData).IsRequired();
            entity.Property(e => e.PublishStatus)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.ProviderSourceDataset).WithMany(p => p.ProviderSourceDatasetVersions)
                .HasForeignKey(d => d.ProviderSourceDatasetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProviderSourceDatasetVersions_ProviderSourceDataset");
        });

        modelBuilder.Entity<ProviderSpecificationResult>(entity =>
        {
            entity.HasKey(e => e.ProviderSpecificationResultsId);

            entity.ToTable("ProviderSpecificationResults", "dbo");

            entity.HasIndex(e => new { e.ProviderId, e.SpecificationId }, "IX_PSR_Provider_Spec");

            entity.Property(e => e.ProviderId)
                .IsRequired()
                .HasMaxLength(16);
            entity.Property(e => e.ProviderVersionId).HasMaxLength(128);
            entity.Property(e => e.SpecificationId)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.SpecificationName)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.FundingPeriod).WithMany(p => p.ProviderSpecificationResults)
                .HasForeignKey(d => d.FundingPeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PSR_FundingPeriod");

            entity.HasOne(d => d.FundingStreamIdsNavigation).WithMany(p => p.ProviderSpecificationResults)
                .HasForeignKey(d => d.FundingStreamIds)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PSR_FundingStream");

            entity.HasOne(d => d.Specification).WithMany(p => p.ProviderSpecificationResults)
                .HasForeignKey(d => d.SpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PSR_Specification");
        });

        modelBuilder.Entity<ProviderTypeSubType>(entity =>
        {
            entity.ToTable("ProviderTypeSubTypes", "dbo");

            entity.HasIndex(e => e.FundingStreamPeriodProfilePatternId, "IX_ProviderTypeSubTypes_FundingStreamPeriodProfilePatternId");

            entity.Property(e => e.FundingStreamPeriodProfilePatternId)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ProviderSubType)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ProviderType)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.FundingStreamPeriodProfilePattern).WithMany(p => p.ProviderTypeSubTypes)
                .HasForeignKey(d => d.FundingStreamPeriodProfilePatternId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProviderTypeSubTypes_FundingStreamPeriodProfilePatterns");
        });

        modelBuilder.Entity<ProviderVersionFundingPeriodDetail>(entity =>
        {
            entity.HasKey(e => e.ProviderVersionFundingPeriodDetailsId);

            entity.ToTable("ProviderVersionFundingPeriodDetails", "dbo");

            entity.Property(e => e.CurrentProviderVersionId)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProviderVersionId)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.CurrentProviderVersion).WithMany(p => p.ProviderVersionFundingPeriodDetails)
                .HasForeignKey(d => d.CurrentProviderVersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProviderVersionFundingPeriodDetails_CurrentProviderVersion");

            entity.HasOne(d => d.FundingPeriod).WithMany(p => p.ProviderVersionFundingPeriodDetails)
                .HasForeignKey(d => d.FundingPeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProviderVersionFundingPeriodDetails_FundingPeriodId");
        });

        modelBuilder.Entity<ProviderVersionMetadatum>(entity =>
        {
            entity.HasKey(e => e.ProviderVersionMetadataId);

            entity.ToTable("ProviderVersionMetadata", "dbo");

            entity.HasIndex(e => e.ProviderVersionId, "UQ_ProviderVersionMetadata_providerVersionId").IsUnique();

            entity.Property(e => e.ProviderVersionMetadataId).HasMaxLength(50);
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ProviderVersionId)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Providers).HasMaxLength(50);
            entity.Property(e => e.VersionType)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.FundingStream).WithMany(p => p.ProviderVersionMetadata)
                .HasForeignKey(d => d.FundingStreamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProviderVersionMetadata_FundingStream");
        });

        modelBuilder.Entity<ReProfilingConfigurationProperty>(entity =>
        {
            entity.HasKey(e => new { e.FundingStreamPeriodProfilePatternId, e.PropertyName });

            entity.ToTable("ReProfilingConfigurationProperties", "dbo");

            entity.Property(e => e.FundingStreamPeriodProfilePatternId).HasMaxLength(255);
            entity.Property(e => e.PropertyName).HasMaxLength(100);
            entity.Property(e => e.PropertyValue)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.FundingStreamPeriodProfilePattern).WithMany(p => p.ReProfilingConfigurationProperties)
                .HasForeignKey(d => d.FundingStreamPeriodProfilePatternId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReProfilingConfigurationProperties_FundingStreamPeriodProfilePatterns");
        });

        modelBuilder.Entity<Specification>(entity =>
        {
            entity.ToTable("Specifications", "dbo");

            entity.HasIndex(e => e.FundingPeriodId, "IX_Specifications_FundingPeriodId");

            entity.HasIndex(e => e.FundingStreamId, "IX_Specifications_FundingStreamId");

            entity.Property(e => e.SpecificationId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.SpecificationName)
                .IsRequired()
                .HasMaxLength(256);

            entity.HasOne(d => d.FundingPeriod).WithMany(p => p.Specifications)
                .HasForeignKey(d => d.FundingPeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Specifications_FundingPeriods");

            entity.HasOne(d => d.FundingStream).WithMany(p => p.Specifications)
                .HasForeignKey(d => d.FundingStreamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Specifications_FundingStreams");
        });

        modelBuilder.Entity<SpecificationVersion>(entity =>
        {
            entity.ToTable("SpecificationVersions", "dbo");

            entity.HasIndex(e => new { e.SpecificationId, e.IsDeleted }, "IX_SpecificationVersions_SpecificationId_IsDeleted");

            entity.Property(e => e.SpecificationVersionId)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.AuthorId)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.AuthorName)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.CoreProviderVersionUpdates)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProviderSource).HasMaxLength(50);
            entity.Property(e => e.ProviderVersionId).HasMaxLength(255);
            entity.Property(e => e.PublishStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SpecificationId)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.SpecificationName)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.TemplateVersion).HasColumnType("decimal(18, 1)");

            entity.HasOne(d => d.Specification).WithMany(p => p.SpecificationVersions)
                .HasForeignKey(d => d.SpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SpecificationVersions_Specifications");
        });

        modelBuilder.Entity<Successor>(entity =>
        {
            entity.ToTable("Successors", "dbo");

            entity.Property(e => e.ProviderId)
                .IsRequired()
                .HasMaxLength(16);
            entity.Property(e => e.ProviderVersionId)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.Ukprn)
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnName("UKPRN");

            entity.HasOne(d => d.Provider).WithMany(p => p.Successors)
                .HasPrincipalKey(p => new { p.ProviderId, p.ProviderVersionId })
                .HasForeignKey(d => new { d.ProviderId, d.ProviderVersionId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Successors_ToProvider");
        });

        modelBuilder.Entity<Template>(entity =>
        {
            entity.ToTable("Templates", "dbo");

            entity.Property(e => e.TemplateId).ValueGeneratedNever();
            entity.Property(e => e.AuthorId)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.AuthorName)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.EntityId)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.PublishStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SchemaVersion)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.FundingPeriod).WithMany(p => p.Templates)
                .HasForeignKey(d => d.FundingPeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Templates_FundingPeriods");

            entity.HasOne(d => d.FundingStream).WithMany(p => p.Templates)
                .HasForeignKey(d => d.FundingStreamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Templates_FundingStreams");
        });

        modelBuilder.Entity<TemplateMapping>(entity =>
        {
            entity.ToTable("TemplateMappings", "dbo");

            entity.Property(e => e.TemplateMappingId).HasMaxLength(255);
            entity.Property(e => e.SpecificationId)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);

            entity.HasOne(d => d.FundingStream).WithMany(p => p.TemplateMappings)
                .HasForeignKey(d => d.FundingStreamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TemplateMappings_FundingStreams");

            entity.HasOne(d => d.Specification).WithMany(p => p.TemplateMappings)
                .HasForeignKey(d => d.SpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TemplateMappings_Specifications");
        });

        modelBuilder.Entity<TemplateMappingItem>(entity =>
        {
            entity.ToTable("TemplateMappingItems", "dbo");

            entity.Property(e => e.CalculationId).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.TemplateMappingId)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<TemplatePredecessor>(entity =>
        {
            entity.HasKey(e => e.PredecessorId).HasName("PK__tmp_ms_x__0C49EF463D30D5A8");

            entity.ToTable("TemplatePredecessors", "dbo");

            entity.Property(e => e.TemplateVersionId)
                .IsRequired()
                .HasMaxLength(512);

            entity.HasOne(d => d.Template).WithMany(p => p.TemplatePredecessors)
                .HasForeignKey(d => d.TemplateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TemplatePredecessors_Templates");

            entity.HasOne(d => d.TemplateVersion).WithMany(p => p.TemplatePredecessors)
                .HasForeignKey(d => d.TemplateVersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TemplatePredecessors_TemplateVersions");
        });

        modelBuilder.Entity<TemplateVersion>(entity =>
        {
            entity.ToTable("TemplateVersions", "dbo");

            entity.Property(e => e.TemplateVersionId).HasMaxLength(512);
            entity.Property(e => e.AuthorId)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.AuthorName)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.EntityId)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.PublishStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SchemaVersion)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.FundingPeriod).WithMany(p => p.TemplateVersions)
                .HasForeignKey(d => d.FundingPeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TemplateVersions_FundingPeriods");

            entity.HasOne(d => d.FundingStream).WithMany(p => p.TemplateVersions)
                .HasForeignKey(d => d.FundingStreamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TemplateVersions_FundingStreams");

            entity.HasOne(d => d.Template).WithMany(p => p.TemplateVersions)
                .HasForeignKey(d => d.TemplateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TemplateVersions_Templates");
        });

        modelBuilder.Entity<VariationPointer>(entity =>
        {
            entity.HasKey(e => e.ProfileVariationPointerId);

            entity.ToTable("VariationPointers", "dbo");

            entity.HasIndex(e => new { e.SpecificationVersionId, e.IsDeleted }, "IX_VariationPointers_SpecificationId_IsDeleted");

            entity.Property(e => e.FundingLineId)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PeriodType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PeriodValue)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SpecificationVersionId)
                .IsRequired()
                .HasMaxLength(512)
                .IsUnicode(false);

            entity.HasOne(d => d.SpecificationVersion).WithMany(p => p.VariationPointers)
                .HasForeignKey(d => d.SpecificationVersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VariationPointers_SpecificationVersions");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}