// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class CurrentProviderVersion
{
    public string CurrentProviderVersionId { get; set; }

    public string ProviderVersionId { get; set; }

    public int? ProviderSnapshotId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ProviderVersionFundingPeriodDetail> ProviderVersionFundingPeriodDetails { get; set; } = new List<ProviderVersionFundingPeriodDetail>();
}