// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class DatasetDefinition
{
    public string Id { get; set; }

    public string Name { get; set; }

    public int Version { get; set; }

    public string Description { get; set; }

    public int FundingStreamId { get; set; }

    public bool ConverterEligible { get; set; }

    public bool ValidateProviders { get; set; }

    public int? ValidateProvidersByYearRange { get; set; }

    public string TableDefinitions { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual FundingStream FundingStream { get; set; }
}