// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class DatasetAggregation
{
    public string DatasetAggregationId { get; set; }

    public string SpecificationId { get; set; }

    public string DatasetRelationshipId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<DatasetAggregationField> DatasetAggregationFields { get; set; } = new List<DatasetAggregationField>();

    public virtual Specification Specification { get; set; }
}