// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class DatasetAggregationField
{
    public int Id { get; set; }

    public string DatasetAggregationId { get; set; }

    public string FieldType { get; set; }

    public decimal Value { get; set; }

    public string FieldDefinitionName { get; set; }

    public virtual DatasetAggregation DatasetAggregation { get; set; }
}