// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class DatasetVersion
{
    public string DatasetVersionId { get; set; }

    public string DatasetId { get; set; }

    public string BlobName { get; set; }

    public int RowCount { get; set; }

    public int NewRowCount { get; set; }

    public int AmendedRowCount { get; set; }

    public string UploadedBlobFilePath { get; set; }

    public string ChangeType { get; set; }

    public int FundingStreamId { get; set; }

    public string ProviderVersionId { get; set; }

    public string Description { get; set; }

    public int Version { get; set; }

    public DateTime Date { get; set; }

    public string AuthorId { get; set; }

    public string AuthorName { get; set; }

    public string Comment { get; set; }

    public string PublishStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsLatest { get; set; }

    public virtual Dataset Dataset { get; set; }

    public virtual FundingStream FundingStream { get; set; }
}