// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class DatasetSpecificationRelationship
{
    public string DatasetSpecificationRelationshipVersionId { get; set; }

    public string DatasetSpecificationRelationshipId { get; set; }

    public string Name { get; set; }

    public string DatasetDefinitionId { get; set; }

    public string DatasetDefinitionName { get; set; }

    public string SpecificationId { get; set; }

    public string PublishedSpecificationId { get; set; }

    public string Description { get; set; }

    public string DatasetId { get; set; }

    public int? DatasetVersionNumber { get; set; }

    public bool IsSetAsProviderData { get; set; }

    public bool ConverterEnabled { get; set; }

    public bool UsedInDataAggregations { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string RelationshipType { get; set; }

    public string PublishedSpecificationConfiguration { get; set; }

    public int Version { get; set; }

    public string AuthorId { get; set; }

    public string AuthorName { get; set; }

    public string Comment { get; set; }

    public string PublishStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsLatest { get; set; }

    public string FundingPeriodName { get; set; }

    public virtual Specification Specification { get; set; }
}