// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class FundingStreamPeriodProfilePattern
{
    public string Id { get; set; }

    public int FundingPeriodId { get; set; }

    public int FundingStreamId { get; set; }

    public string FundingLineId { get; set; }

    public string ProfilePatternKey { get; set; }

    public string ProfilePatternType { get; set; }

    public string RoundingStrategy { get; set; }

    public DateTime FundingStreamPeriodStartDate { get; set; }

    public DateTime FundingStreamPeriodEndDate { get; set; }

    public bool AllowUserToEditProfilePattern { get; set; }

    public string ProfilePatternOpenDateConfig { get; set; }

    public string ProfilePatternDisplayName { get; set; }

    public string ProfilePatternDescription { get; set; }

    public string ProfileCacheEtag { get; set; }

    public string Etag { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual FundingPeriod FundingPeriod { get; set; }

    public virtual FundingStream FundingStream { get; set; }

    public virtual ICollection<ProfilePatternPeriod> ProfilePatternPeriods { get; set; } = new List<ProfilePatternPeriod>();

    public virtual ICollection<ProviderTypeSubType> ProviderTypeSubTypes { get; set; } = new List<ProviderTypeSubType>();

    public virtual ICollection<ReProfilingConfigurationProperty> ReProfilingConfigurationProperties { get; set; } = new List<ReProfilingConfigurationProperty>();
}