// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class FundingLineResult
{
    public int FundingLineResultId { get; set; }

    public string FundingLineId { get; set; }

    public string FundingLineName { get; set; }

    public string FundingLineFundingStreamId { get; set; }

    public string Value { get; set; }

    public string ExceptionType { get; set; }

    public string ExceptionMessage { get; set; }

    public string ExceptionStackTrace { get; set; }

    public string ProviderResultId { get; set; }

    public virtual ProviderResult ProviderResult { get; set; }
}