// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class FundingStream
{
    public int FundingStreamId { get; set; }

    public string FundingStreamCode { get; set; }

    public string FundingStreamName { get; set; }

    public string ShortFundingStreamName { get; set; }

    public virtual ICollection<Calculation> Calculations { get; set; } = new List<Calculation>();

    public virtual ICollection<DatasetDefinition> DatasetDefinitions { get; set; } = new List<DatasetDefinition>();

    public virtual ICollection<DatasetVersion> DatasetVersions { get; set; } = new List<DatasetVersion>();

    public virtual ICollection<FundingStreamPeriodProfilePattern> FundingStreamPeriodProfilePatterns { get; set; } = new List<FundingStreamPeriodProfilePattern>();

    public virtual ICollection<ObsoleteItem> ObsoleteItems { get; set; } = new List<ObsoleteItem>();

    public virtual ICollection<ProviderSpecificationResult> ProviderSpecificationResults { get; set; } = new List<ProviderSpecificationResult>();

    public virtual ICollection<ProviderVersionMetadatum> ProviderVersionMetadata { get; set; } = new List<ProviderVersionMetadatum>();

    public virtual ICollection<Specification> Specifications { get; set; } = new List<Specification>();

    public virtual ICollection<TemplateMapping> TemplateMappings { get; set; } = new List<TemplateMapping>();

    public virtual ICollection<TemplateVersion> TemplateVersions { get; set; } = new List<TemplateVersion>();

    public virtual ICollection<Template> Templates { get; set; } = new List<Template>();
}