// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class FundingPeriod
{
    public int FundingPeriodId { get; set; }

    public string FundingPeriodCode { get; set; }

    public string FundingPeriodName { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Period { get; set; }

    public string Type { get; set; }

    public int? StartYear { get; set; }

    public int? EndYear { get; set; }

    public virtual ICollection<FundingStreamPeriodProfilePattern> FundingStreamPeriodProfilePatterns { get; set; } = new List<FundingStreamPeriodProfilePattern>();

    public virtual ICollection<ProviderSpecificationResult> ProviderSpecificationResults { get; set; } = new List<ProviderSpecificationResult>();

    public virtual ICollection<ProviderVersionFundingPeriodDetail> ProviderVersionFundingPeriodDetails { get; set; } = new List<ProviderVersionFundingPeriodDetail>();

    public virtual ICollection<Specification> Specifications { get; set; } = new List<Specification>();

    public virtual ICollection<TemplateVersion> TemplateVersions { get; set; } = new List<TemplateVersion>();

    public virtual ICollection<Template> Templates { get; set; } = new List<Template>();
}