// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class ObsoleteItemCalc
{
    public int Id { get; set; }

    public string ObsoleteItemId { get; set; }

    public string CalculationId { get; set; }

    public virtual Calculation Calculation { get; set; }

    public virtual ObsoleteItem ObsoleteItem { get; set; }
}