// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class ObsoleteItem
{
    public string ObsoleteItemId { get; set; }

    public string SpecificationId { get; set; }

    public string DatasetRelationshipId { get; set; }

    public string DatasetRelationshipName { get; set; }

    public string DatasetFieldId { get; set; }

    public string DatasetFieldName { get; set; }

    public string DatasetDataType { get; set; }

    public bool? IsReleasedData { get; set; }

    public string RelationshipName { get; set; }

    public string ItemType { get; set; }

    public string EnumValueName { get; set; }

    public int? FundingLineId { get; set; }

    public int FundingStreamId { get; set; }

    public int? TemplateCalculationId { get; set; }

    public string CodeReference { get; set; }

    public string FundingLineName { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual FundingStream FundingStream { get; set; }

    public virtual ICollection<ObsoleteItemCalc> ObsoleteItemCalcs { get; set; } = new List<ObsoleteItemCalc>();

    public virtual Specification Specification { get; set; }
}