// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class Policy
{
    public int Id { get; set; }

    public string PolicyId { get; set; }

    public string DocumentType { get; set; }

    public string Content { get; set; }

    public int FundingPeriodId { get; set; }

    public int FundingStreamId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }
}