// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class ProfilePatternPeriod
{
    public int ProfilePatternPeriodId { get; set; }

    public string FundingStreamPeriodProfilePatternId { get; set; }

    public string PeriodType { get; set; }

    public string Period { get; set; }

    public DateTime PeriodStartDate { get; set; }

    public DateTime PeriodEndDate { get; set; }

    public int PeriodYear { get; set; }

    public int Occurrence { get; set; }

    public string DistributionPeriod { get; set; }

    public string PeriodPatternPercentage { get; set; }

    public int? PeriodPatternCalculationId { get; set; }

    public virtual FundingStreamPeriodProfilePattern FundingStreamPeriodProfilePattern { get; set; }
}