// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class Provider
{
    public int Id { get; set; }

    public string ProviderId { get; set; }

    public string Name { get; set; }

    public string ProviderVersionId { get; set; }

    public string Urn { get; set; }

    public string Ukprn { get; set; }

    public string Upin { get; set; }

    public string EstablishmentNumber { get; set; }

    public string DfeEstablishmentNumber { get; set; }

    public string Authority { get; set; }

    public string ProviderType { get; set; }

    public string ProviderSubType { get; set; }

    public DateTime? DateOpened { get; set; }

    public DateTime? DateClosed { get; set; }

    public string ProviderProfileIdType { get; set; }

    public string LaCode { get; set; }

    public string LaOrg { get; set; }

    public string NavVendorNo { get; set; }

    public string CrmAccountId { get; set; }

    public string LegalName { get; set; }

    public string Status { get; set; }

    public string PhaseOfEducation { get; set; }

    public string ReasonEstablishmentOpened { get; set; }

    public string ReasonEstablishmentClosed { get; set; }

    public string Successor { get; set; }

    public string TrustStatus { get; set; }

    public string TrustName { get; set; }

    public string TrustCode { get; set; }

    public string Town { get; set; }

    public string Postcode { get; set; }

    public string CompaniesHouseNumber { get; set; }

    public string GroupIdNumber { get; set; }

    public string RscRegionName { get; set; }

    public string RscRegionCode { get; set; }

    public string GovernmentOfficeRegionName { get; set; }

    public string GovernmentOfficeRegionCode { get; set; }

    public string DistrictName { get; set; }

    public string DistrictCode { get; set; }

    public string WardName { get; set; }

    public string WardCode { get; set; }

    public string CensusWardName { get; set; }

    public string CensusWardCode { get; set; }

    public string MiddleSuperOutputAreaName { get; set; }

    public string MiddleSuperOutputAreaCode { get; set; }

    public string LowerSuperOutputAreaName { get; set; }

    public string LowerSuperOutputAreaCode { get; set; }

    public string ParliamentaryConstituencyName { get; set; }

    public string ParliamentaryConstituencyCode { get; set; }

    public string LondonRegionName { get; set; }

    public string LondonRegionCode { get; set; }

    public string CountyName { get; set; }

    public string CountyCode { get; set; }

    public string LocalGovernmentGroupTypeName { get; set; }

    public string LocalGovernmentGroupTypeCode { get; set; }

    public string Street { get; set; }

    public string Locality { get; set; }

    public string Address3 { get; set; }

    public string PaymentOrganisationIdentifier { get; set; }

    public string PaymentOrganisationName { get; set; }

    public string ProviderTypeCode { get; set; }

    public string ProviderSubTypeCode { get; set; }

    public string PreviousLaCode { get; set; }

    public string PreviousLaName { get; set; }

    public string PreviousEstablishmentNumber { get; set; }

    public string FurtherEducationTypeName { get; set; }

    public string FurtherEducationTypeCode { get; set; }

    public string PhaseOfEducationCode { get; set; }

    public string StatutoryLowAge { get; set; }

    public string StatutoryHighAge { get; set; }

    public string OfficialSixthFormCode { get; set; }

    public string OfficialSixthFormName { get; set; }

    public string StatusCode { get; set; }

    public string ReasonEstablishmentOpenedCode { get; set; }

    public string ReasonEstablishmentClosedCode { get; set; }

    public virtual ICollection<Predecessor> Predecessors { get; set; } = new List<Predecessor>();

    public virtual ICollection<ProviderResult> ProviderResults { get; set; } = new List<ProviderResult>();

    public virtual ICollection<Successor> Successors { get; set; } = new List<Successor>();
}