// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class ProviderVersionFundingPeriodDetail
{
    public int ProviderVersionFundingPeriodDetailsId { get; set; }

    public string CurrentProviderVersionId { get; set; }

    public int FundingPeriodId { get; set; }

    public int ProviderSnapshotId { get; set; }

    public string ProviderVersionId { get; set; }

    public virtual CurrentProviderVersion CurrentProviderVersion { get; set; }

    public virtual FundingPeriod FundingPeriod { get; set; }
}