// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class ProviderSpecificationResult
{
    public int ProviderSpecificationResultsId { get; set; }

    public string ProviderId { get; set; }

    public string ProviderVersionId { get; set; }

    public string SpecificationId { get; set; }

    public string SpecificationName { get; set; }

    public DateTime? LastEditDate { get; set; }

    public int FundingPeriodId { get; set; }

    public int FundingStreamIds { get; set; }

    public DateTime FundingPeriodEnd { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual FundingPeriod FundingPeriod { get; set; }

    public virtual FundingStream FundingStreamIdsNavigation { get; set; }

    public virtual Specification Specification { get; set; }
}