// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class ProviderSourceDataset
{
    public string ProviderSourceDatasetId { get; set; }

    public string ProviderId { get; set; }

    public string SpecificationId { get; set; }

    public string DataDefinitionId { get; set; }

    public string DatasetRelationshipSummaryId { get; set; }

    public string DataRelationshipSummaryName { get; set; }

    public string DataGranularity { get; set; }

    public bool? DefinesScope { get; set; }

    public bool IsDeleted { get; set; }

    public string DatasetRelationshipType { get; set; }

    public virtual ICollection<ProviderSourceDatasetVersion> ProviderSourceDatasetVersions { get; set; } = new List<ProviderSourceDatasetVersion>();

    public virtual Specification Specification { get; set; }
}