// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class ProviderSourceDatasetVersion
{
    public string ProviderSourceDatasetVersionId { get; set; }

    public string ProviderSourceDatasetId { get; set; }

    public string DatasetId { get; set; }

    public string DatasetName { get; set; }

    public int DatasetVersion { get; set; }

    public string ProviderSourceDatasetRowData { get; set; }

    public int Version { get; set; }

    public string AuthorId { get; set; }

    public string AuthorName { get; set; }

    public string Comment { get; set; }

    public string PublishStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime Date { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsLatest { get; set; }

    public virtual ProviderSourceDataset ProviderSourceDataset { get; set; }
}