// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class ProviderResult
{
    public string ProviderResultId { get; set; }

    public DateTime CreatedAt { get; set; }

    public string SpecificationId { get; set; }

    public bool? IsIndicativeProvider { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public string ProviderId { get; set; }

    public string ProviderVersionId { get; set; }

    public virtual ICollection<CalcResult> CalcResults { get; set; } = new List<CalcResult>();

    public virtual ICollection<FundingLineResult> FundingLineResults { get; set; } = new List<FundingLineResult>();

    public virtual Provider Provider { get; set; }

    public virtual Specification Specification { get; set; }
}