// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class ProviderVersionMetadatum
{
    public string ProviderVersionMetadataId { get; set; }

    public string Providers { get; set; }

    public string ProviderVersionId { get; set; }

    public string VersionType { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int Version { get; set; }

    public DateTime TargetDate { get; set; }

    public int FundingStreamId { get; set; }

    public string ValidationResult { get; set; }

    public DateTime Created { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual FundingStream FundingStream { get; set; }
}