// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class ProviderTypeSubType
{
    public int ProviderTypeSubTypeId { get; set; }

    public string FundingStreamPeriodProfilePatternId { get; set; }

    public string ProviderType { get; set; }

    public string ProviderSubType { get; set; }

    public virtual FundingStreamPeriodProfilePattern FundingStreamPeriodProfilePattern { get; set; }
}