// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class ReProfilingConfigurationProperty
{
    public string FundingStreamPeriodProfilePatternId { get; set; }

    public string PropertyName { get; set; }

    public string PropertyValue { get; set; }

    public virtual FundingStreamPeriodProfilePattern FundingStreamPeriodProfilePattern { get; set; }
}