// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class Specification
{
    public string SpecificationId { get; set; }

    public string SpecificationName { get; set; }

    public int FundingStreamId { get; set; }

    public int FundingPeriodId { get; set; }

    public bool IsSelectedForFunding { get; set; }

    public bool ForceUpdateOnNextRefresh { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Calculation> Calculations { get; set; } = new List<Calculation>();

    public virtual ICollection<DatasetAggregation> DatasetAggregations { get; set; } = new List<DatasetAggregation>();

    public virtual ICollection<DatasetSpecificationRelationship> DatasetSpecificationRelationships { get; set; } = new List<DatasetSpecificationRelationship>();

    public virtual FundingPeriod FundingPeriod { get; set; }

    public virtual FundingStream FundingStream { get; set; }

    public virtual ICollection<ObsoleteItem> ObsoleteItems { get; set; } = new List<ObsoleteItem>();

    public virtual ICollection<ProviderResult> ProviderResults { get; set; } = new List<ProviderResult>();

    public virtual ICollection<ProviderSourceDataset> ProviderSourceDatasets { get; set; } = new List<ProviderSourceDataset>();

    public virtual ICollection<ProviderSpecificationResult> ProviderSpecificationResults { get; set; } = new List<ProviderSpecificationResult>();

    public virtual ICollection<SpecificationVersion> SpecificationVersions { get; set; } = new List<SpecificationVersion>();

    public virtual ICollection<TemplateMapping> TemplateMappings { get; set; } = new List<TemplateMapping>();
}