// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class SpecificationVersion
{
    public string SpecificationVersionId { get; set; }

    public string SpecificationId { get; set; }

    public string SpecificationName { get; set; }

    public string ProviderVersionId { get; set; }

    public decimal? TemplateVersion { get; set; }

    public int Version { get; set; }

    public string Description { get; set; }

    public DateTime? ExternalPublicationDate { get; set; }

    public DateTime? EarliestPaymentAvailableDate { get; set; }

    public string ProviderSource { get; set; }

    public int? ProviderSnapshotId { get; set; }

    public string CoreProviderVersionUpdates { get; set; }

    public DateTime Date { get; set; }

    public string AuthorId { get; set; }

    public string AuthorName { get; set; }

    public string Comment { get; set; }

    public string PublishStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsLatest { get; set; }

    public virtual ICollection<DefinitionSpecificationRelationship> DefinitionSpecificationRelationships { get; set; } = new List<DefinitionSpecificationRelationship>();

    public virtual Specification Specification { get; set; }

    public virtual ICollection<VariationPointer> VariationPointers { get; set; } = new List<VariationPointer>();
}