// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class Successor
{
    public int SuccessorId { get; set; }

    public string ProviderId { get; set; }

    public string Ukprn { get; set; }

    public string ProviderVersionId { get; set; }

    public virtual Provider Provider { get; set; }
}