// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class Template
{
    public Guid TemplateId { get; set; }

    public string Description { get; set; }

    public string TemplateJson { get; set; }

    public int MajorVersion { get; set; }

    public int MinorVersion { get; set; }

    public string Name { get; set; }

    public string SchemaVersion { get; set; }

    public string EntityId { get; set; }

    public string Status { get; set; }

    public int Version { get; set; }

    public DateTime Date { get; set; }

    public string Comment { get; set; }

    public string PublishStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public int FundingStreamId { get; set; }

    public int FundingPeriodId { get; set; }

    public string AuthorId { get; set; }

    public string AuthorName { get; set; }

    public virtual FundingPeriod FundingPeriod { get; set; }

    public virtual FundingStream FundingStream { get; set; }

    public virtual ICollection<TemplatePredecessor> TemplatePredecessors { get; set; } = new List<TemplatePredecessor>();

    public virtual ICollection<TemplateVersion> TemplateVersions { get; set; } = new List<TemplateVersion>();
}