// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class TemplateMappingItem
{
    public int TemplateMappingItemId { get; set; }

    public string TemplateMappingId { get; set; }

    public int EntityType { get; set; }

    public string Name { get; set; }

    public int TemplateId { get; set; }

    public string CalculationId { get; set; }
}