// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class TemplateMapping
{
    public string TemplateMappingId { get; set; }

    public string SpecificationId { get; set; }

    public int FundingStreamId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual FundingStream FundingStream { get; set; }

    public virtual Specification Specification { get; set; }
}