// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class TemplatePredecessor
{
    public int PredecessorId { get; set; }

    public Guid TemplateId { get; set; }

    public string TemplateVersionId { get; set; }

    public virtual Template Template { get; set; }

    public virtual TemplateVersion TemplateVersion { get; set; }
}