// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateFunding.Repositories.Common.EFCore.EntityModel;

public partial class VariationPointer
{
    public int ProfileVariationPointerId { get; set; }

    public string SpecificationVersionId { get; set; }

    public string FundingLineId { get; set; }

    public string PeriodType { get; set; }

    public string PeriodValue { get; set; }

    public int Year { get; set; }

    public int Occurrence { get; set; }

    public bool IsDeleted { get; set; }

    public virtual SpecificationVersion SpecificationVersion { get; set; }
}