// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CalculateFunding.Publishing.AcceptanceTests.Features.ReleaseManagement
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ReleaseManagement_InitialReleaseFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "ReleaseManagement-InitialRelease.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/ReleaseManagement", "ReleaseManagement-InitialRelease", "Release providers to one or more channels - no providers have existing releases", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "ReleaseManagement-InitialRelease")))
            {
                global::CalculateFunding.Publishing.AcceptanceTests.Features.ReleaseManagement.ReleaseManagement_InitialReleaseFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void InitialReleaseOfProvidersIntoChannels_SingleProviderInApprovedState(string fundingStreamId, string fundingPeriodId, string specificationId, string specificationName, string providerVersionId, string providerSnapshotId, string currentDateTime, string authorId, string authorName, string correlationId, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "releasemanagement"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("FundingStreamId", fundingStreamId);
            argumentsOfScenario.Add("FundingPeriodId", fundingPeriodId);
            argumentsOfScenario.Add("SpecificationId", specificationId);
            argumentsOfScenario.Add("Specification Name", specificationName);
            argumentsOfScenario.Add("ProviderVersionId", providerVersionId);
            argumentsOfScenario.Add("ProviderSnapshotId", providerSnapshotId);
            argumentsOfScenario.Add("CurrentDateTime", currentDateTime);
            argumentsOfScenario.Add("AuthorId", authorId);
            argumentsOfScenario.Add("AuthorName", authorName);
            argumentsOfScenario.Add("CorrelationId", correlationId);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Initial release of providers into channels - single provider in Approved state", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1167 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProviderId"});
                table1167.AddRow(new string[] {
                            string.Format("{0}-{1}-10071688", fundingStreamId, fundingPeriodId)});
#line 7
 testRunner.Given("funding is released for providers", ((string)(null)), table1167, "Given ");
#line hidden
#line 10
 testRunner.And("release management repo has prereq data populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1168 = new TechTalk.SpecFlow.Table(new string[] {
                            "Statement"});
                table1168.AddRow(new string[] {
                            "Payment"});
#line 11
 testRunner.And("funding is released for channels", ((string)(null)), table1168, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1169 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1169.AddRow(new string[] {
                            "Id",
                            string.Format("{0}", specificationId)});
                table1169.AddRow(new string[] {
                            "Name",
                            "<SpecificationName>"});
                table1169.AddRow(new string[] {
                            "IsSelectedForFunding",
                            "true"});
                table1169.AddRow(new string[] {
                            "ProviderVersionId",
                            string.Format("{0}", providerVersionId)});
                table1169.AddRow(new string[] {
                            "ProviderSnapshotId",
                            string.Format("{0}", providerSnapshotId)});
                table1169.AddRow(new string[] {
                            "FundingStreamId",
                            string.Format("{0}", fundingStreamId)});
                table1169.AddRow(new string[] {
                            "FundingPeriodId",
                            string.Format("{0}", fundingPeriodId)});
                table1169.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
#line 14
 testRunner.And("the following specification exists", ((string)(null)), table1169, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1170 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1170.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1170.AddRow(new string[] {
                            "SpecificationName",
                            "<SpecificationName>"});
                table1170.AddRow(new string[] {
                            "FundingStreamId",
                            string.Format("{0}", fundingStreamId)});
                table1170.AddRow(new string[] {
                            "FundingPeriodId",
                            string.Format("{0}", fundingPeriodId)});
#line 24
 testRunner.And("the following specification exists in release management", ((string)(null)), table1170, "And ");
#line hidden
#line 30
 testRunner.And(string.Format("published provider \'10071688\' exists for funding stream \'{0}\' in period \'{1}\' in " +
                            "cosmos from json", fundingStreamId, fundingPeriodId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
 testRunner.And(string.Format("a funding configuration exists for funding stream \'{0}\' in funding period \'{1}\' i" +
                            "n resources in file modifier \'Batch\'", fundingStreamId, fundingPeriodId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1171 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1171.AddRow(new string[] {
                            "Period",
                            "2122"});
                table1171.AddRow(new string[] {
                            "Type",
                            "AY"});
                table1171.AddRow(new string[] {
                            "ID",
                            string.Format("{0}", fundingPeriodId)});
                table1171.AddRow(new string[] {
                            "StartDate",
                            "2021-09-01 00:00:00"});
                table1171.AddRow(new string[] {
                            "EndDate",
                            "2022-08-31 23:59:59"});
#line 32
 testRunner.And("the funding period exists in the policies service", ((string)(null)), table1171, "And ");
#line hidden
#line 39
 testRunner.And(string.Format("the provider version \'{0}\' exists in the provider service for \'{0}\'", providerVersionId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 40
 testRunner.And(string.Format("all providers in provider version \'{0}\' are in scope", providerVersionId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 41
 testRunner.And(string.Format("the payment organisations are available for provider snapshot \'{0}\' from FDZ", providerSnapshotId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1172 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1172.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
#line 42
 testRunner.And("the following job is requested to be queued for the current specification", ((string)(null)), table1172, "And ");
#line hidden
#line 45
 testRunner.And("the job is submitted to the job service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 46
 testRunner.And(string.Format("the current date and time is \'{0}\'", currentDateTime), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1173 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1173.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1173.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1173.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
#line 47
 testRunner.When("funding is released to channels for selected providers", ((string)(null)), table1173, "When ");
#line hidden
                TechTalk.SpecFlow.Table table1174 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1174.AddRow(new string[] {
                            "ReleasedProviderId",
                            "00000000-0000-0000-0000-000000000001"});
                table1174.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1174.AddRow(new string[] {
                            "ProviderId",
                            "10071688"});
#line 53
 testRunner.Then("there is a released provider record in the release management repository", ((string)(null)), table1174, "Then ");
#line hidden
#line 58
 testRunner.And("there is a total of \'1\' released provider records in the release management repoi" +
                        "story", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1175 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1175.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1175.AddRow(new string[] {
                            "ReleasedProviderId",
                            "00000000-0000-0000-0000-000000000001"});
                table1175.AddRow(new string[] {
                            "MajorVersion",
                            "1"});
                table1175.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-10071688-1_0"});
                table1175.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1175.AddRow(new string[] {
                            "CoreProviderVersionId",
                            string.Format("{0}", providerVersionId)});
#line 60
 testRunner.And("there is a released provider version record created in the release management rep" +
                        "ository", ((string)(null)), table1175, "And ");
#line hidden
#line 68
 testRunner.And("there is a total of \'1\' released provider version records in the release manageme" +
                        "nt repoistory", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1176 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1176.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000001"});
                table1176.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1176.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1176.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1176.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
                table1176.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1176.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 70
 testRunner.And("there is a released provider version channel record created in the release manage" +
                        "ment repository", ((string)(null)), table1176, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1177 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1177.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000002"});
                table1177.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1177.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1177.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1177.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
                table1177.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1177.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 79
 testRunner.And("there is a released provider version channel record created in the release manage" +
                        "ment repository", ((string)(null)), table1177, "And ");
#line hidden
#line 88
 testRunner.And("there are a total of \'2\' released provider version channel records created in the" +
                        " release management repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1178 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1178.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000001"});
                table1178.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
                table1178.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000001"});
#line 90
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1178, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1179 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1179.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000002"});
                table1179.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
                table1179.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000001"});
#line 95
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1179, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1180 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1180.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000003"});
                table1180.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
                table1180.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000002"});
#line 100
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1180, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1181 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1181.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000004"});
                table1181.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
                table1181.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000002"});
#line 105
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1181, "And ");
#line hidden
#line 110
 testRunner.And("there are a total of \'4\' released provider version channel variation reason recor" +
                        "ds created in the release management repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1182 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1182.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000001"});
                table1182.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1182.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1182.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1182.AddRow(new string[] {
                            "OrganisationGroupTypeCode",
                            "LocalAuthority"});
                table1182.AddRow(new string[] {
                            "OrganisationGroupTypeIdentifier",
                            "UKPRN"});
                table1182.AddRow(new string[] {
                            "OrganisationGroupIdentifierValue",
                            "10004002"});
                table1182.AddRow(new string[] {
                            "OrganisationGroupName",
                            "WANDSWORTH LONDON BOROUGH COUNCIL"});
                table1182.AddRow(new string[] {
                            "OrganisationGroupSearchableName",
                            "WANDSWORTH_LONDON_BOROUGH_COUNCIL"});
                table1182.AddRow(new string[] {
                            "OrganisationGroupTypeClassification",
                            "LegalEntity"});
#line 112
 testRunner.And("there is a funding group created in the release management repository", ((string)(null)), table1182, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1183 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1183.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000002"});
                table1183.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1183.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1183.AddRow(new string[] {
                            "GroupingReason",
                            "Information"});
                table1183.AddRow(new string[] {
                            "OrganisationGroupTypeCode",
                            "LocalAuthority"});
                table1183.AddRow(new string[] {
                            "OrganisationGroupTypeIdentifier",
                            "LACode"});
                table1183.AddRow(new string[] {
                            "OrganisationGroupIdentifierValue",
                            "212"});
                table1183.AddRow(new string[] {
                            "OrganisationGroupName",
                            "Wandsworth"});
                table1183.AddRow(new string[] {
                            "OrganisationGroupSearchableName",
                            "Wandsworth"});
                table1183.AddRow(new string[] {
                            "OrganisationGroupTypeClassification",
                            "GeographicalBoundary"});
#line 124
 testRunner.And("there is a funding group created in the release management repository", ((string)(null)), table1183, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1184 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1184.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000003"});
                table1184.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1184.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1184.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1184.AddRow(new string[] {
                            "OrganisationGroupTypeCode",
                            "LocalAuthority"});
                table1184.AddRow(new string[] {
                            "OrganisationGroupTypeIdentifier",
                            "UKPRN"});
                table1184.AddRow(new string[] {
                            "OrganisationGroupIdentifierValue",
                            "10004002"});
                table1184.AddRow(new string[] {
                            "OrganisationGroupName",
                            "WANDSWORTH LONDON BOROUGH COUNCIL"});
                table1184.AddRow(new string[] {
                            "OrganisationGroupSearchableName",
                            "WANDSWORTH_LONDON_BOROUGH_COUNCIL"});
                table1184.AddRow(new string[] {
                            "OrganisationGroupTypeClassification",
                            "LegalEntity"});
#line 136
 testRunner.And("there is a funding group created in the release management repository", ((string)(null)), table1184, "And ");
#line hidden
#line 148
 testRunner.And("there are a total of \'3\' funding group records created in the release management " +
                        "repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1185 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1185.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1185.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000001"});
                table1185.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1185.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1185.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1185.AddRow(new string[] {
                            "MajorVersion",
                            "1"});
                table1185.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1185.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1185.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1185.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1185.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1185.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1185.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1185.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Payment-LocalAuthority-10004002-1_0"});
                table1185.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1185.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1185.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1185.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 150
 testRunner.And("there is a funding group version created in the release management repository", ((string)(null)), table1185, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1186 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1186.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000002"});
                table1186.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000002"});
                table1186.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1186.AddRow(new string[] {
                            "GroupingReason",
                            "Information"});
                table1186.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1186.AddRow(new string[] {
                            "MajorVersion",
                            "1"});
                table1186.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1186.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1186.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1186.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1186.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1186.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1186.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1186.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Information-LocalAuthority-212-1_0"});
                table1186.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1186.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1186.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1186.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 170
 testRunner.And("there is a funding group version created in the release management repository", ((string)(null)), table1186, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1187 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1187.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000003"});
                table1187.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000003"});
                table1187.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1187.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1187.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1187.AddRow(new string[] {
                            "MajorVersion",
                            "1"});
                table1187.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1187.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1187.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1187.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1187.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1187.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1187.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1187.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Payment-LocalAuthority-10004002-1_0"});
                table1187.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1187.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1187.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1187.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 190
 testRunner.And("there is a funding group version created in the release management repository", ((string)(null)), table1187, "And ");
#line hidden
#line 210
 testRunner.And("there are a total of \'3\' funding group version records created in the release man" +
                        "agement repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1188 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1188.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000001"});
                table1188.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1188.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
#line 212
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1188, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1189 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1189.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000002"});
                table1189.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1189.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
#line 217
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1189, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1190 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1190.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000003"});
                table1190.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000002"});
                table1190.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
#line 222
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1190, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1191 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1191.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000004"});
                table1191.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000002"});
                table1191.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
#line 227
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1191, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1192 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1192.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000005"});
                table1192.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000003"});
                table1192.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
#line 232
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1192, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1193 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1193.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000006"});
                table1193.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000003"});
                table1193.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
#line 237
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1193, "And ");
#line hidden
#line 242
 testRunner.And("there are a total of \'6\' funding group version variation reason records created i" +
                        "n the release management repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1194 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1194.AddRow(new string[] {
                            "FundingGroupProviderId",
                            "00000000-0000-0000-0000-000000000001"});
                table1194.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1194.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000001"});
#line 244
 testRunner.And("there is the provider version associated with the funding group version in the re" +
                        "lease management repository", ((string)(null)), table1194, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1195 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1195.AddRow(new string[] {
                            "FundingGroupProviderId",
                            "00000000-0000-0000-0000-000000000002"});
                table1195.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000002"});
                table1195.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000001"});
#line 249
 testRunner.And("there is the provider version associated with the funding group version in the re" +
                        "lease management repository", ((string)(null)), table1195, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1196 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1196.AddRow(new string[] {
                            "FundingGroupProviderId",
                            "00000000-0000-0000-0000-000000000003"});
                table1196.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000003"});
                table1196.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000002"});
#line 254
 testRunner.And("there is the provider version associated with the funding group version in the re" +
                        "lease management repository", ((string)(null)), table1196, "And ");
#line hidden
#line 259
 testRunner.And("there are a total of \'3\' funding group providers created in the release managemen" +
                        "t repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 261
 testRunner.And("there is content blob created for the funding group with ID \'PSG-AY-2122-Informat" +
                        "ion-LocalAuthority-212-1_0\' in the channel \'Statement\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 262
 testRunner.And("there is content blob created for the funding group with ID \'PSG-AY-2122-Payment-" +
                        "LocalAuthority-10004002-1_0\' in the channel \'Statement\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 263
 testRunner.And("there is content blob created for the funding group with ID \'PSG-AY-2122-Payment-" +
                        "LocalAuthority-10004002-1_0\' in the channel \'Payment\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 264
 testRunner.And("there are \'3\' files contained in the funding groups blob storage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 266
 testRunner.And("there is content blob created for the released published provider with ID \'PSG-AY" +
                        "-2122-10071688-1_0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 267
 testRunner.And("there are \'1\' files contained in the published providers blob storage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 269
 testRunner.And("there is content blob created for the released provider with ID \'PSG-AY-2122-1007" +
                        "1688-1_0\' in channel \'Payment\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 270
 testRunner.And("there is content blob created for the released provider with ID \'PSG-AY-2122-1007" +
                        "1688-1_0\' in channel \'Statement\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 271
 testRunner.And("there are \'2\' files contained in the released providers blob storage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Initial release of providers into channels - single provider in Approved state: P" +
            "SG")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ReleaseManagement-InitialRelease")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("releasemanagement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "PSG")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FundingStreamId", "PSG")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FundingPeriodId", "AY-2122")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SpecificationId", "3812005f-13b3-4d00-a118-d6cb0e2b2402")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Specification Name", "PE and Sport Grant")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProviderVersionId", "PSG-2021-10-11-76")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProviderSnapshotId", "76")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CurrentDateTime", "2022-02-10 14:18:00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AuthorId", "AuthId")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AuthorName", "Author Name")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CorrelationId", "Corr")]
        public virtual void InitialReleaseOfProvidersIntoChannels_SingleProviderInApprovedState_PSG()
        {
#line 6
this.InitialReleaseOfProvidersIntoChannels_SingleProviderInApprovedState("PSG", "AY-2122", "3812005f-13b3-4d00-a118-d6cb0e2b2402", "PE and Sport Grant", "PSG-2021-10-11-76", "76", "2022-02-10 14:18:00", "AuthId", "Author Name", "Corr", ((string[])(null)));
#line hidden
        }
        
        public virtual void InitialReleaseOfProvidersIntoChannels_SingleProviderInReleasedStateEgAlreadyReleasedToAnotherChannel(string fundingStreamId, string fundingPeriodId, string specificationId, string specificationName, string providerVersionId, string providerSnapshotId, string currentDateTime, string authorId, string authorName, string correlationId, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "releasemanagement"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("FundingStreamId", fundingStreamId);
            argumentsOfScenario.Add("FundingPeriodId", fundingPeriodId);
            argumentsOfScenario.Add("SpecificationId", specificationId);
            argumentsOfScenario.Add("Specification Name", specificationName);
            argumentsOfScenario.Add("ProviderVersionId", providerVersionId);
            argumentsOfScenario.Add("ProviderSnapshotId", providerSnapshotId);
            argumentsOfScenario.Add("CurrentDateTime", currentDateTime);
            argumentsOfScenario.Add("AuthorId", authorId);
            argumentsOfScenario.Add("AuthorName", authorName);
            argumentsOfScenario.Add("CorrelationId", correlationId);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Initial release of providers into channels - single provider in Released state (e" +
                    "g already released to another channel)", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 280
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1197 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProviderId"});
                table1197.AddRow(new string[] {
                            string.Format("{0}-{1}-10071689", fundingStreamId, fundingPeriodId)});
#line 281
 testRunner.Given("funding is released for providers", ((string)(null)), table1197, "Given ");
#line hidden
#line 284
 testRunner.And("release management repo has prereq data populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1198 = new TechTalk.SpecFlow.Table(new string[] {
                            "Statement"});
                table1198.AddRow(new string[] {
                            "Payment"});
#line 285
 testRunner.And("funding is released for channels", ((string)(null)), table1198, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1199 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1199.AddRow(new string[] {
                            "Id",
                            string.Format("{0}", specificationId)});
                table1199.AddRow(new string[] {
                            "Name",
                            "<SpecificationName>"});
                table1199.AddRow(new string[] {
                            "IsSelectedForFunding",
                            "true"});
                table1199.AddRow(new string[] {
                            "ProviderVersionId",
                            string.Format("{0}", providerVersionId)});
                table1199.AddRow(new string[] {
                            "ProviderSnapshotId",
                            string.Format("{0}", providerSnapshotId)});
                table1199.AddRow(new string[] {
                            "FundingStreamId",
                            string.Format("{0}", fundingStreamId)});
                table1199.AddRow(new string[] {
                            "FundingPeriodId",
                            string.Format("{0}", fundingPeriodId)});
                table1199.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
#line 288
 testRunner.And("the following specification exists", ((string)(null)), table1199, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1200 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1200.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1200.AddRow(new string[] {
                            "SpecificationName",
                            "<SpecificationName>"});
                table1200.AddRow(new string[] {
                            "FundingStreamId",
                            string.Format("{0}", fundingStreamId)});
                table1200.AddRow(new string[] {
                            "FundingPeriodId",
                            string.Format("{0}", fundingPeriodId)});
#line 298
 testRunner.And("the following specification exists in release management", ((string)(null)), table1200, "And ");
#line hidden
#line 304
 testRunner.And(string.Format("published provider \'10071689\' exists for funding stream \'{0}\' in period \'{1}\' in " +
                            "cosmos from json", fundingStreamId, fundingPeriodId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 305
 testRunner.And(string.Format("a funding configuration exists for funding stream \'{0}\' in funding period \'{1}\' i" +
                            "n resources in file modifier \'Batch\'", fundingStreamId, fundingPeriodId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1201 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1201.AddRow(new string[] {
                            "Period",
                            "2122"});
                table1201.AddRow(new string[] {
                            "Type",
                            "AY"});
                table1201.AddRow(new string[] {
                            "ID",
                            string.Format("{0}", fundingPeriodId)});
                table1201.AddRow(new string[] {
                            "StartDate",
                            "2021-09-01 00:00:00"});
                table1201.AddRow(new string[] {
                            "EndDate",
                            "2022-08-31 23:59:59"});
#line 306
 testRunner.And("the funding period exists in the policies service", ((string)(null)), table1201, "And ");
#line hidden
#line 313
 testRunner.And(string.Format("the provider version \'{0}\' exists in the provider service for \'{0}\'", providerVersionId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 314
 testRunner.And(string.Format("all providers in provider version \'{0}\' are in scope", providerVersionId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 315
 testRunner.And(string.Format("the payment organisations are available for provider snapshot \'{0}\' from FDZ", providerSnapshotId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1202 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1202.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
#line 316
 testRunner.And("the following job is requested to be queued for the current specification", ((string)(null)), table1202, "And ");
#line hidden
#line 319
 testRunner.And("the job is submitted to the job service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 320
 testRunner.And(string.Format("the current date and time is \'{0}\'", currentDateTime), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1203 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1203.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1203.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1203.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
#line 321
 testRunner.When("funding is released to channels for selected providers", ((string)(null)), table1203, "When ");
#line hidden
                TechTalk.SpecFlow.Table table1204 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1204.AddRow(new string[] {
                            "ReleasedProviderId",
                            "00000000-0000-0000-0000-000000000001"});
                table1204.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1204.AddRow(new string[] {
                            "ProviderId",
                            "10071689"});
#line 327
 testRunner.Then("there is a released provider record in the release management repository", ((string)(null)), table1204, "Then ");
#line hidden
#line 332
 testRunner.And("there is a total of \'1\' released provider records in the release management repoi" +
                        "story", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1205 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1205.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1205.AddRow(new string[] {
                            "ReleasedProviderId",
                            "00000000-0000-0000-0000-000000000001"});
                table1205.AddRow(new string[] {
                            "MajorVersion",
                            "1"});
                table1205.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-10071689-1_0"});
                table1205.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1205.AddRow(new string[] {
                            "CoreProviderVersionId",
                            string.Format("{0}", providerVersionId)});
#line 334
 testRunner.And("there is a released provider version record created in the release management rep" +
                        "ository", ((string)(null)), table1205, "And ");
#line hidden
#line 342
 testRunner.And("there is a total of \'1\' released provider version records in the release manageme" +
                        "nt repoistory", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1206 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1206.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000001"});
                table1206.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1206.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1206.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1206.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
                table1206.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1206.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 344
 testRunner.And("there is a released provider version channel record created in the release manage" +
                        "ment repository", ((string)(null)), table1206, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1207 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1207.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000002"});
                table1207.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1207.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1207.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1207.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
                table1207.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1207.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 353
 testRunner.And("there is a released provider version channel record created in the release manage" +
                        "ment repository", ((string)(null)), table1207, "And ");
#line hidden
#line 362
 testRunner.And("there are a total of \'2\' released provider version channel records created in the" +
                        " release management repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1208 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1208.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000001"});
                table1208.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
                table1208.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000001"});
#line 364
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1208, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1209 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1209.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000002"});
                table1209.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
                table1209.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000001"});
#line 369
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1209, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1210 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1210.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000003"});
                table1210.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
                table1210.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000002"});
#line 374
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1210, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1211 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1211.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000004"});
                table1211.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
                table1211.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000002"});
#line 379
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1211, "And ");
#line hidden
#line 384
 testRunner.And("there are a total of \'4\' released provider version channel variation reason recor" +
                        "ds created in the release management repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1212 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1212.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000001"});
                table1212.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1212.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1212.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1212.AddRow(new string[] {
                            "OrganisationGroupTypeCode",
                            "LocalAuthority"});
                table1212.AddRow(new string[] {
                            "OrganisationGroupTypeIdentifier",
                            "UKPRN"});
                table1212.AddRow(new string[] {
                            "OrganisationGroupIdentifierValue",
                            "10004002"});
                table1212.AddRow(new string[] {
                            "OrganisationGroupName",
                            "WANDSWORTH LONDON BOROUGH COUNCIL"});
                table1212.AddRow(new string[] {
                            "OrganisationGroupSearchableName",
                            "WANDSWORTH_LONDON_BOROUGH_COUNCIL"});
                table1212.AddRow(new string[] {
                            "OrganisationGroupTypeClassification",
                            "LegalEntity"});
#line 386
 testRunner.And("there is a funding group created in the release management repository", ((string)(null)), table1212, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1213 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1213.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000002"});
                table1213.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1213.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1213.AddRow(new string[] {
                            "GroupingReason",
                            "Information"});
                table1213.AddRow(new string[] {
                            "OrganisationGroupTypeCode",
                            "LocalAuthority"});
                table1213.AddRow(new string[] {
                            "OrganisationGroupTypeIdentifier",
                            "LACode"});
                table1213.AddRow(new string[] {
                            "OrganisationGroupIdentifierValue",
                            "212"});
                table1213.AddRow(new string[] {
                            "OrganisationGroupName",
                            "Wandsworth"});
                table1213.AddRow(new string[] {
                            "OrganisationGroupSearchableName",
                            "Wandsworth"});
                table1213.AddRow(new string[] {
                            "OrganisationGroupTypeClassification",
                            "GeographicalBoundary"});
#line 398
 testRunner.And("there is a funding group created in the release management repository", ((string)(null)), table1213, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1214 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1214.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000003"});
                table1214.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1214.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1214.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1214.AddRow(new string[] {
                            "OrganisationGroupTypeCode",
                            "LocalAuthority"});
                table1214.AddRow(new string[] {
                            "OrganisationGroupTypeIdentifier",
                            "UKPRN"});
                table1214.AddRow(new string[] {
                            "OrganisationGroupIdentifierValue",
                            "10004002"});
                table1214.AddRow(new string[] {
                            "OrganisationGroupName",
                            "WANDSWORTH LONDON BOROUGH COUNCIL"});
                table1214.AddRow(new string[] {
                            "OrganisationGroupSearchableName",
                            "WANDSWORTH_LONDON_BOROUGH_COUNCIL"});
                table1214.AddRow(new string[] {
                            "OrganisationGroupTypeClassification",
                            "LegalEntity"});
#line 410
 testRunner.And("there is a funding group created in the release management repository", ((string)(null)), table1214, "And ");
#line hidden
#line 422
 testRunner.And("there are a total of \'3\' funding group records created in the release management " +
                        "repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1215 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1215.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1215.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000001"});
                table1215.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1215.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1215.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1215.AddRow(new string[] {
                            "MajorVersion",
                            "1"});
                table1215.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1215.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1215.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1215.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1215.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1215.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1215.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1215.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Payment-LocalAuthority-10004002-1_0"});
                table1215.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1215.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1215.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1215.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 424
 testRunner.And("there is a funding group version created in the release management repository", ((string)(null)), table1215, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1216 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1216.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000002"});
                table1216.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000002"});
                table1216.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1216.AddRow(new string[] {
                            "GroupingReason",
                            "Information"});
                table1216.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1216.AddRow(new string[] {
                            "MajorVersion",
                            "1"});
                table1216.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1216.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1216.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1216.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1216.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1216.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1216.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1216.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Information-LocalAuthority-212-1_0"});
                table1216.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1216.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1216.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1216.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 444
 testRunner.And("there is a funding group version created in the release management repository", ((string)(null)), table1216, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1217 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1217.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000003"});
                table1217.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000003"});
                table1217.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1217.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1217.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1217.AddRow(new string[] {
                            "MajorVersion",
                            "1"});
                table1217.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1217.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1217.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1217.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1217.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1217.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1217.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1217.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Payment-LocalAuthority-10004002-1_0"});
                table1217.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1217.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1217.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1217.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 464
 testRunner.And("there is a funding group version created in the release management repository", ((string)(null)), table1217, "And ");
#line hidden
#line 484
 testRunner.And("there are a total of \'3\' funding group version records created in the release man" +
                        "agement repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1218 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1218.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000001"});
                table1218.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1218.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
#line 486
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1218, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1219 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1219.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000002"});
                table1219.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1219.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
#line 491
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1219, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1220 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1220.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000003"});
                table1220.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000002"});
                table1220.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
#line 496
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1220, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1221 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1221.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000004"});
                table1221.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000002"});
                table1221.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
#line 501
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1221, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1222 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1222.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000005"});
                table1222.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000003"});
                table1222.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
#line 506
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1222, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1223 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1223.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000006"});
                table1223.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000003"});
                table1223.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
#line 511
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1223, "And ");
#line hidden
#line 516
 testRunner.And("there are a total of \'6\' funding group version variation reason records created i" +
                        "n the release management repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1224 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1224.AddRow(new string[] {
                            "FundingGroupProviderId",
                            "00000000-0000-0000-0000-000000000001"});
                table1224.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1224.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000001"});
#line 518
 testRunner.And("there is the provider version associated with the funding group version in the re" +
                        "lease management repository", ((string)(null)), table1224, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1225 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1225.AddRow(new string[] {
                            "FundingGroupProviderId",
                            "00000000-0000-0000-0000-000000000002"});
                table1225.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000002"});
                table1225.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000001"});
#line 523
 testRunner.And("there is the provider version associated with the funding group version in the re" +
                        "lease management repository", ((string)(null)), table1225, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1226 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1226.AddRow(new string[] {
                            "FundingGroupProviderId",
                            "00000000-0000-0000-0000-000000000003"});
                table1226.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000003"});
                table1226.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000002"});
#line 528
 testRunner.And("there is the provider version associated with the funding group version in the re" +
                        "lease management repository", ((string)(null)), table1226, "And ");
#line hidden
#line 533
 testRunner.And("there are a total of \'3\' funding group providers created in the release managemen" +
                        "t repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 535
 testRunner.And("there is content blob created for the funding group with ID \'PSG-AY-2122-Informat" +
                        "ion-LocalAuthority-212-1_0\' in the channel \'Statement\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 536
 testRunner.And("there is content blob created for the funding group with ID \'PSG-AY-2122-Payment-" +
                        "LocalAuthority-10004002-1_0\' in the channel \'Statement\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 537
 testRunner.And("there is content blob created for the funding group with ID \'PSG-AY-2122-Payment-" +
                        "LocalAuthority-10004002-1_0\' in the channel \'Payment\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 538
 testRunner.And("there are \'3\' files contained in the funding groups blob storage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 540
 testRunner.And("there are \'0\' files contained in the published providers blob storage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 542
 testRunner.And("there is content blob created for the released provider with ID \'PSG-AY-2122-1007" +
                        "1689-1_0\' in channel \'Payment\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 543
 testRunner.And("there is content blob created for the released provider with ID \'PSG-AY-2122-1007" +
                        "1689-1_0\' in channel \'Statement\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 544
 testRunner.And("there are \'2\' files contained in the released providers blob storage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Initial release of providers into channels - single provider in Released state (e" +
            "g already released to another channel): PSG")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ReleaseManagement-InitialRelease")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("releasemanagement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "PSG")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FundingStreamId", "PSG")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FundingPeriodId", "AY-2122")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SpecificationId", "3812005f-13b3-4d00-a118-d6cb0e2b2402")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Specification Name", "PE and Sport Grant")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProviderVersionId", "PSG-2021-10-11-77")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProviderSnapshotId", "77")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CurrentDateTime", "2022-02-10 14:18:00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AuthorId", "AuthId")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AuthorName", "Author Name")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CorrelationId", "Corr")]
        public virtual void InitialReleaseOfProvidersIntoChannels_SingleProviderInReleasedStateEgAlreadyReleasedToAnotherChannel_PSG()
        {
#line 280
this.InitialReleaseOfProvidersIntoChannels_SingleProviderInReleasedStateEgAlreadyReleasedToAnotherChannel("PSG", "AY-2122", "3812005f-13b3-4d00-a118-d6cb0e2b2402", "PE and Sport Grant", "PSG-2021-10-11-77", "77", "2022-02-10 14:18:00", "AuthId", "Author Name", "Corr", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
