// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CalculateFunding.Publishing.AcceptanceTests.Features.ReleaseManagement
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ReleaseManagement_SubsequentRelease_MultipleChannelsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "ReleaseManagement-SubsequentRelease-MultipleChannels.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/ReleaseManagement", "ReleaseManagement-Subsequent release - multiple channels", "Release providers to one or more channels - one or more provider already has a ve" +
                    "rsion released in more or more channels", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "ReleaseManagement-Subsequent release - multiple channels")))
            {
                global::CalculateFunding.Publishing.AcceptanceTests.Features.ReleaseManagement.ReleaseManagement_SubsequentRelease_MultipleChannelsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ReleaseANewMajorVersionOfAProviderWhichHasAlreadyBeenReleasedInTwoChannels(string fundingStreamId, string fundingPeriodId, string specificationId, string specificationName, string providerVersionId, string providerSnapshotId, string currentDateTime, string authorId, string authorName, string correlationId, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "releasemanagement"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("FundingStreamId", fundingStreamId);
            argumentsOfScenario.Add("FundingPeriodId", fundingPeriodId);
            argumentsOfScenario.Add("SpecificationId", specificationId);
            argumentsOfScenario.Add("Specification Name", specificationName);
            argumentsOfScenario.Add("ProviderVersionId", providerVersionId);
            argumentsOfScenario.Add("ProviderSnapshotId", providerSnapshotId);
            argumentsOfScenario.Add("CurrentDateTime", currentDateTime);
            argumentsOfScenario.Add("AuthorId", authorId);
            argumentsOfScenario.Add("AuthorName", authorName);
            argumentsOfScenario.Add("CorrelationId", correlationId);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Release a new major version of a provider which has already been released in two " +
                    "channels", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1227 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProviderId"});
                table1227.AddRow(new string[] {
                            string.Format("{0}-{1}-10071690", fundingStreamId, fundingPeriodId)});
#line 7
 testRunner.Given("funding is released for providers", ((string)(null)), table1227, "Given ");
#line hidden
#line 10
 testRunner.And("release management repo has prereq data populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1228 = new TechTalk.SpecFlow.Table(new string[] {
                            "Statement"});
                table1228.AddRow(new string[] {
                            "Payment"});
#line 11
 testRunner.And("funding is released for channels", ((string)(null)), table1228, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1229 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1229.AddRow(new string[] {
                            "Id",
                            string.Format("{0}", specificationId)});
                table1229.AddRow(new string[] {
                            "Name",
                            "<SpecificationName>"});
                table1229.AddRow(new string[] {
                            "IsSelectedForFunding",
                            "true"});
                table1229.AddRow(new string[] {
                            "ProviderVersionId",
                            string.Format("{0}", providerVersionId)});
                table1229.AddRow(new string[] {
                            "ProviderSnapshotId",
                            string.Format("{0}", providerSnapshotId)});
                table1229.AddRow(new string[] {
                            "FundingStreamId",
                            string.Format("{0}", fundingStreamId)});
                table1229.AddRow(new string[] {
                            "FundingPeriodId",
                            string.Format("{0}", fundingPeriodId)});
                table1229.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
#line 14
 testRunner.And("the following specification exists", ((string)(null)), table1229, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1230 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1230.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1230.AddRow(new string[] {
                            "SpecificationName",
                            "<SpecificationName>"});
                table1230.AddRow(new string[] {
                            "FundingStreamId",
                            string.Format("{0}", fundingStreamId)});
                table1230.AddRow(new string[] {
                            "FundingPeriodId",
                            string.Format("{0}", fundingPeriodId)});
#line 24
 testRunner.And("the following specification exists in release management", ((string)(null)), table1230, "And ");
#line hidden
#line 30
 testRunner.And(string.Format("published provider \'10071690\' exists for funding stream \'{0}\' in period \'{1}\' in " +
                            "cosmos from json", fundingStreamId, fundingPeriodId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
 testRunner.And(string.Format("published provider version with major version \'2\' for provider id \'10071690\' exis" +
                            "ts for funding stream \'{0}\' in period \'{1}\' in cosmos from json", fundingStreamId, fundingPeriodId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
 testRunner.And(string.Format("a funding configuration exists for funding stream \'{0}\' in funding period \'{1}\' i" +
                            "n resources in file modifier \'Batch\'", fundingStreamId, fundingPeriodId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1231 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1231.AddRow(new string[] {
                            "Period",
                            "2122"});
                table1231.AddRow(new string[] {
                            "Type",
                            "AY"});
                table1231.AddRow(new string[] {
                            "ID",
                            string.Format("{0}", fundingPeriodId)});
                table1231.AddRow(new string[] {
                            "StartDate",
                            "2021-09-01 00:00:00"});
                table1231.AddRow(new string[] {
                            "EndDate",
                            "2022-08-31 23:59:59"});
#line 33
 testRunner.And("the funding period exists in the policies service", ((string)(null)), table1231, "And ");
#line hidden
#line 40
 testRunner.And(string.Format("the provider version \'{0}\' exists in the provider service for \'{0}\'", providerVersionId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 41
 testRunner.And(string.Format("all providers in provider version \'{0}\' are in scope", providerVersionId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 42
 testRunner.And(string.Format("the payment organisations are available for provider snapshot \'{0}\' from FDZ", providerSnapshotId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1232 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1232.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
#line 43
 testRunner.And("the following job is requested to be queued for the current specification", ((string)(null)), table1232, "And ");
#line hidden
#line 46
 testRunner.And("the job is submitted to the job service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 47
 testRunner.And(string.Format("the current date and time is \'{0}\'", currentDateTime), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1233 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1233.AddRow(new string[] {
                            "ReleasedProviderId",
                            "00000000-0000-0000-0000-000000000001"});
                table1233.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1233.AddRow(new string[] {
                            "ProviderId",
                            "10071690"});
#line 49
 testRunner.And("there is a released provider record in the release management repository", ((string)(null)), table1233, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1234 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1234.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1234.AddRow(new string[] {
                            "ReleasedProviderId",
                            "00000000-0000-0000-0000-000000000001"});
                table1234.AddRow(new string[] {
                            "MajorVersion",
                            "1"});
                table1234.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-10071690-1_0"});
                table1234.AddRow(new string[] {
                            "TotalFunding",
                            "16000"});
                table1234.AddRow(new string[] {
                            "CoreProviderVersionId",
                            string.Format("{0}", providerVersionId)});
#line 55
 testRunner.And("a released provider version exists in the release management repository", ((string)(null)), table1234, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1235 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1235.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000002"});
                table1235.AddRow(new string[] {
                            "ReleasedProviderId",
                            "00000000-0000-0000-0000-000000000001"});
                table1235.AddRow(new string[] {
                            "MajorVersion",
                            "2"});
                table1235.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-10071690-1_0"});
                table1235.AddRow(new string[] {
                            "TotalFunding",
                            "17000"});
                table1235.AddRow(new string[] {
                            "CoreProviderVersionId",
                            string.Format("{0}", providerVersionId)});
#line 63
 testRunner.And("a released provider version exists in the release management repository", ((string)(null)), table1235, "And ");
#line hidden
#line 71
 testRunner.And("the next released provider version identifier for new records should be 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1236 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1236.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000001"});
                table1236.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1236.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1236.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1236.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
                table1236.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1236.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 73
 testRunner.And("a released provider version channel record exists in the release management repos" +
                        "itory", ((string)(null)), table1236, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1237 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1237.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000002"});
                table1237.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1237.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1237.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1237.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
                table1237.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1237.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 82
 testRunner.And("a released provider version channel record exists in the release management repos" +
                        "itory", ((string)(null)), table1237, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1238 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1238.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000003"});
                table1238.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000002"});
                table1238.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1238.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1238.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
                table1238.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1238.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 91
 testRunner.And("a released provider version channel record exists in the release management repos" +
                        "itory", ((string)(null)), table1238, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1239 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1239.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000004"});
                table1239.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000002"});
                table1239.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1239.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1239.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
                table1239.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1239.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 100
 testRunner.And("a released provider version channel record exists in the release management repos" +
                        "itory", ((string)(null)), table1239, "And ");
#line hidden
#line 109
 testRunner.And("the next released provider version channel identifier for new records should be 5" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1240 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1240.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000001"});
                table1240.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1240.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1240.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1240.AddRow(new string[] {
                            "OrganisationGroupTypeCode",
                            "LocalAuthority"});
                table1240.AddRow(new string[] {
                            "OrganisationGroupTypeIdentifier",
                            "UKPRN"});
                table1240.AddRow(new string[] {
                            "OrganisationGroupIdentifierValue",
                            "10004002"});
                table1240.AddRow(new string[] {
                            "OrganisationGroupName",
                            "WANDSWORTH LONDON BOROUGH COUNCIL"});
                table1240.AddRow(new string[] {
                            "OrganisationGroupSearchableName",
                            "WANDSWORTH_LONDON_BOROUGH_COUNCIL"});
                table1240.AddRow(new string[] {
                            "OrganisationGroupTypeClassification",
                            "LegalEntity"});
#line 112
 testRunner.And("a funding group record exists in the release management repository", ((string)(null)), table1240, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1241 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1241.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000002"});
                table1241.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1241.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1241.AddRow(new string[] {
                            "GroupingReason",
                            "Information"});
                table1241.AddRow(new string[] {
                            "OrganisationGroupTypeCode",
                            "LocalAuthority"});
                table1241.AddRow(new string[] {
                            "OrganisationGroupTypeIdentifier",
                            "LACode"});
                table1241.AddRow(new string[] {
                            "OrganisationGroupIdentifierValue",
                            "212"});
                table1241.AddRow(new string[] {
                            "OrganisationGroupName",
                            "Wandsworth"});
                table1241.AddRow(new string[] {
                            "OrganisationGroupSearchableName",
                            "Wandsworth"});
                table1241.AddRow(new string[] {
                            "OrganisationGroupTypeClassification",
                            "GeographicalBoundary"});
#line 124
 testRunner.And("a funding group record exists in the release management repository", ((string)(null)), table1241, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1242 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1242.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000003"});
                table1242.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1242.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1242.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1242.AddRow(new string[] {
                            "OrganisationGroupTypeCode",
                            "LocalAuthority"});
                table1242.AddRow(new string[] {
                            "OrganisationGroupTypeIdentifier",
                            "UKPRN"});
                table1242.AddRow(new string[] {
                            "OrganisationGroupIdentifierValue",
                            "10004002"});
                table1242.AddRow(new string[] {
                            "OrganisationGroupName",
                            "WANDSWORTH LONDON BOROUGH COUNCIL"});
                table1242.AddRow(new string[] {
                            "OrganisationGroupSearchableName",
                            "WANDSWORTH_LONDON_BOROUGH_COUNCIL"});
                table1242.AddRow(new string[] {
                            "OrganisationGroupTypeClassification",
                            "LegalEntity"});
#line 136
 testRunner.And("a funding group record exists in the release management repository", ((string)(null)), table1242, "And ");
#line hidden
#line 148
 testRunner.And("a total of \'3\' funding group records exist in the release management repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1243 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1243.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000001"});
                table1243.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000001"});
                table1243.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1243.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1243.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1243.AddRow(new string[] {
                            "MajorVersion",
                            "1"});
                table1243.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1243.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1243.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1243.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1243.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1243.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1243.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1243.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Payment-LocalAuthority-10004002-1_0"});
                table1243.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1243.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1243.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1243.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 150
 testRunner.And("a funding group version exists in the release management repository", ((string)(null)), table1243, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1244 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1244.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000002"});
                table1244.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000002"});
                table1244.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1244.AddRow(new string[] {
                            "GroupingReason",
                            "Information"});
                table1244.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1244.AddRow(new string[] {
                            "MajorVersion",
                            "1"});
                table1244.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1244.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1244.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1244.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1244.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1244.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1244.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1244.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Information-LocalAuthority-212-1_0"});
                table1244.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1244.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1244.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1244.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 170
 testRunner.And("a funding group version exists in the release management repository", ((string)(null)), table1244, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1245 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1245.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000003"});
                table1245.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000003"});
                table1245.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1245.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1245.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1245.AddRow(new string[] {
                            "MajorVersion",
                            "1"});
                table1245.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1245.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1245.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1245.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1245.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1245.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1245.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1245.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Payment-LocalAuthority-10004002-1_0"});
                table1245.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1245.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1245.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1245.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 190
 testRunner.And("a funding group version exists in the release management repository", ((string)(null)), table1245, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1246 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1246.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000004"});
                table1246.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000001"});
                table1246.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1246.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1246.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1246.AddRow(new string[] {
                            "MajorVersion",
                            "2"});
                table1246.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1246.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1246.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1246.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1246.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1246.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1246.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1246.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Payment-LocalAuthority-10004002-2_0"});
                table1246.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1246.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1246.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1246.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 210
 testRunner.And("a funding group version exists in the release management repository", ((string)(null)), table1246, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1247 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1247.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000005"});
                table1247.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000002"});
                table1247.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1247.AddRow(new string[] {
                            "GroupingReason",
                            "Information"});
                table1247.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1247.AddRow(new string[] {
                            "MajorVersion",
                            "2"});
                table1247.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1247.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1247.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1247.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1247.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1247.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1247.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1247.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Information-LocalAuthority-212-2_0"});
                table1247.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1247.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1247.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1247.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 230
 testRunner.And("a funding group version exists in the release management repository", ((string)(null)), table1247, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1248 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1248.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000006"});
                table1248.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000003"});
                table1248.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1248.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1248.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1248.AddRow(new string[] {
                            "MajorVersion",
                            "2"});
                table1248.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1248.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1248.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1248.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1248.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1248.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1248.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1248.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Payment-LocalAuthority-10004002-2_0"});
                table1248.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1248.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1248.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1248.AddRow(new string[] {
                            "ChannelVersion",
                            "1"});
#line 250
 testRunner.And("a funding group version exists in the release management repository", ((string)(null)), table1248, "And ");
#line hidden
#line 270
 testRunner.And("the next funding group version identifier for new records should be 7", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 271
 testRunner.And("a total of \'6\' funding group version records exist in the release management repo" +
                        "sitory", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1249 = new TechTalk.SpecFlow.Table(new string[] {
                            "FundingGroupProviderId",
                            "FundingGroupVersionId",
                            "ReleasedProviderVersionChannelId"});
                table1249.AddRow(new string[] {
                            "00000000-0000-0000-0000-000000000001",
                            "00000000-0000-0000-0000-000000000001",
                            "00000000-0000-0000-0000-000000000001"});
                table1249.AddRow(new string[] {
                            "00000000-0000-0000-0000-000000000002",
                            "00000000-0000-0000-0000-000000000002",
                            "00000000-0000-0000-0000-000000000001"});
                table1249.AddRow(new string[] {
                            "00000000-0000-0000-0000-000000000003",
                            "00000000-0000-0000-0000-000000000003",
                            "00000000-0000-0000-0000-000000000002"});
                table1249.AddRow(new string[] {
                            "00000000-0000-0000-0000-000000000004",
                            "00000000-0000-0000-0000-000000000004",
                            "00000000-0000-0000-0000-000000000003"});
                table1249.AddRow(new string[] {
                            "00000000-0000-0000-0000-000000000005",
                            "00000000-0000-0000-0000-000000000005",
                            "00000000-0000-0000-0000-000000000003"});
                table1249.AddRow(new string[] {
                            "00000000-0000-0000-0000-000000000006",
                            "00000000-0000-0000-0000-000000000006",
                            "00000000-0000-0000-0000-000000000004"});
#line 273
 testRunner.And("the provider versions associated with the funding group versions exist in the rel" +
                        "ease management repository", ((string)(null)), table1249, "And ");
#line hidden
#line 281
 testRunner.And("a total of \'6\' funding group providers exist in the release management repository" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 282
 testRunner.And("the next funding group provider identifier for new records should be 7", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1250 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1250.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1250.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1250.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
#line 284
 testRunner.When("funding is released to channels for selected providers", ((string)(null)), table1250, "When ");
#line hidden
                TechTalk.SpecFlow.Table table1251 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1251.AddRow(new string[] {
                            "ReleasedProviderId",
                            "00000000-0000-0000-0000-000000000001"});
                table1251.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1251.AddRow(new string[] {
                            "ProviderId",
                            "10071690"});
#line 290
 testRunner.Then("there is a released provider record in the release management repository", ((string)(null)), table1251, "Then ");
#line hidden
#line 295
 testRunner.And("there is a total of \'1\' released provider records in the release management repoi" +
                        "story", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1252 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1252.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000003"});
                table1252.AddRow(new string[] {
                            "ReleasedProviderId",
                            "00000000-0000-0000-0000-000000000001"});
                table1252.AddRow(new string[] {
                            "MajorVersion",
                            "3"});
                table1252.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-10071690-3_0"});
                table1252.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1252.AddRow(new string[] {
                            "CoreProviderVersionId",
                            string.Format("{0}", providerVersionId)});
#line 297
 testRunner.And("there is a released provider version record created in the release management rep" +
                        "ository", ((string)(null)), table1252, "And ");
#line hidden
#line 305
 testRunner.And("there is a total of \'3\' released provider version records in the release manageme" +
                        "nt repoistory", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1253 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1253.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000005"});
                table1253.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000003"});
                table1253.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1253.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1253.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
                table1253.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1253.AddRow(new string[] {
                            "ChannelVersion",
                            "2"});
#line 307
 testRunner.And("there is a released provider version channel record created in the release manage" +
                        "ment repository", ((string)(null)), table1253, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1254 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1254.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000006"});
                table1254.AddRow(new string[] {
                            "ReleasedProviderVersionId",
                            "00000000-0000-0000-0000-000000000003"});
                table1254.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1254.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1254.AddRow(new string[] {
                            "AuthorId",
                            string.Format("{0}", authorId)});
                table1254.AddRow(new string[] {
                            "AuthorName",
                            string.Format("{0}", authorName)});
                table1254.AddRow(new string[] {
                            "ChannelVersion",
                            "2"});
#line 316
 testRunner.And("there is a released provider version channel record created in the release manage" +
                        "ment repository", ((string)(null)), table1254, "And ");
#line hidden
#line 325
 testRunner.And("there are a total of \'6\' released provider version channel records created in the" +
                        " release management repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1255 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1255.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000001"});
                table1255.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
                table1255.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000005"});
#line 327
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1255, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1256 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1256.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000002"});
                table1256.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
                table1256.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000005"});
#line 332
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1256, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1257 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1257.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000003"});
                table1257.AddRow(new string[] {
                            "VariationReason",
                            "CalculationValuesUpdated"});
                table1257.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000005"});
#line 337
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1257, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1258 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1258.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000004"});
                table1258.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
                table1258.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000006"});
#line 342
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1258, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1259 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1259.AddRow(new string[] {
                            "ReleasedProviderChannelVariationReasonId",
                            "00000000-0000-0000-0000-000000000005"});
                table1259.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
                table1259.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000006"});
#line 347
 testRunner.And("there is a released provider channel variation created in the release management " +
                        "repository", ((string)(null)), table1259, "And ");
#line hidden
#line 352
 testRunner.And("there are a total of \'5\' released provider version channel variation reason recor" +
                        "ds created in the release management repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1260 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1260.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000001"});
                table1260.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1260.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1260.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1260.AddRow(new string[] {
                            "OrganisationGroupTypeCode",
                            "LocalAuthority"});
                table1260.AddRow(new string[] {
                            "OrganisationGroupTypeIdentifier",
                            "UKPRN"});
                table1260.AddRow(new string[] {
                            "OrganisationGroupIdentifierValue",
                            "10004002"});
                table1260.AddRow(new string[] {
                            "OrganisationGroupName",
                            "WANDSWORTH LONDON BOROUGH COUNCIL"});
                table1260.AddRow(new string[] {
                            "OrganisationGroupSearchableName",
                            "WANDSWORTH_LONDON_BOROUGH_COUNCIL"});
                table1260.AddRow(new string[] {
                            "OrganisationGroupTypeClassification",
                            "LegalEntity"});
#line 354
 testRunner.And("there is a funding group created in the release management repository", ((string)(null)), table1260, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1261 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1261.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000002"});
                table1261.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1261.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1261.AddRow(new string[] {
                            "GroupingReason",
                            "Information"});
                table1261.AddRow(new string[] {
                            "OrganisationGroupTypeCode",
                            "LocalAuthority"});
                table1261.AddRow(new string[] {
                            "OrganisationGroupTypeIdentifier",
                            "LACode"});
                table1261.AddRow(new string[] {
                            "OrganisationGroupIdentifierValue",
                            "212"});
                table1261.AddRow(new string[] {
                            "OrganisationGroupName",
                            "Wandsworth"});
                table1261.AddRow(new string[] {
                            "OrganisationGroupSearchableName",
                            "Wandsworth"});
                table1261.AddRow(new string[] {
                            "OrganisationGroupTypeClassification",
                            "GeographicalBoundary"});
#line 366
 testRunner.And("there is a funding group created in the release management repository", ((string)(null)), table1261, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1262 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1262.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000003"});
                table1262.AddRow(new string[] {
                            "SpecificationId",
                            string.Format("{0}", specificationId)});
                table1262.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1262.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1262.AddRow(new string[] {
                            "OrganisationGroupTypeCode",
                            "LocalAuthority"});
                table1262.AddRow(new string[] {
                            "OrganisationGroupTypeIdentifier",
                            "UKPRN"});
                table1262.AddRow(new string[] {
                            "OrganisationGroupIdentifierValue",
                            "10004002"});
                table1262.AddRow(new string[] {
                            "OrganisationGroupName",
                            "WANDSWORTH LONDON BOROUGH COUNCIL"});
                table1262.AddRow(new string[] {
                            "OrganisationGroupSearchableName",
                            "WANDSWORTH_LONDON_BOROUGH_COUNCIL"});
                table1262.AddRow(new string[] {
                            "OrganisationGroupTypeClassification",
                            "LegalEntity"});
#line 378
 testRunner.And("there is a funding group created in the release management repository", ((string)(null)), table1262, "And ");
#line hidden
#line 390
 testRunner.And("there are a total of \'3\' funding group records created in the release management " +
                        "repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1263 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1263.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000007"});
                table1263.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000001"});
                table1263.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1263.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1263.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1263.AddRow(new string[] {
                            "MajorVersion",
                            "3"});
                table1263.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1263.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1263.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1263.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1263.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1263.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1263.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1263.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Payment-LocalAuthority-10004002-3_0"});
                table1263.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1263.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1263.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1263.AddRow(new string[] {
                            "ChannelVersion",
                            "2"});
#line 392
 testRunner.And("there is a funding group version created in the release management repository", ((string)(null)), table1263, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1264 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1264.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000008"});
                table1264.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000002"});
                table1264.AddRow(new string[] {
                            "Channel",
                            "Statement"});
                table1264.AddRow(new string[] {
                            "GroupingReason",
                            "Information"});
                table1264.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1264.AddRow(new string[] {
                            "MajorVersion",
                            "3"});
                table1264.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1264.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1264.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1264.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1264.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1264.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1264.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1264.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Information-LocalAuthority-212-3_0"});
                table1264.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1264.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1264.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1264.AddRow(new string[] {
                            "ChannelVersion",
                            "2"});
#line 412
 testRunner.And("there is a funding group version created in the release management repository", ((string)(null)), table1264, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1265 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1265.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000009"});
                table1265.AddRow(new string[] {
                            "FundingGroupId",
                            "00000000-0000-0000-0000-000000000003"});
                table1265.AddRow(new string[] {
                            "Channel",
                            "Payment"});
                table1265.AddRow(new string[] {
                            "GroupingReason",
                            "Payment"});
                table1265.AddRow(new string[] {
                            "StatusChangedDate",
                            string.Format("{0}", currentDateTime)});
                table1265.AddRow(new string[] {
                            "MajorVersion",
                            "3"});
                table1265.AddRow(new string[] {
                            "MinorVersion",
                            "0"});
                table1265.AddRow(new string[] {
                            "TemplateVersion",
                            "1.2"});
                table1265.AddRow(new string[] {
                            "SchemaVersion",
                            "1.2"});
                table1265.AddRow(new string[] {
                            "JobId",
                            "<JobId>"});
                table1265.AddRow(new string[] {
                            "CorrelationId",
                            string.Format("{0}", correlationId)});
                table1265.AddRow(new string[] {
                            "FundingStreamId",
                            "1"});
                table1265.AddRow(new string[] {
                            "FundingPeriodId",
                            "1"});
                table1265.AddRow(new string[] {
                            "FundingId",
                            "PSG-AY-2122-Payment-LocalAuthority-10004002-3_0"});
                table1265.AddRow(new string[] {
                            "TotalFunding",
                            "17780"});
                table1265.AddRow(new string[] {
                            "ExternalPublicationDate",
                            string.Format("{0}", currentDateTime)});
                table1265.AddRow(new string[] {
                            "EarliestPaymentAvailableDate",
                            string.Format("{0}", currentDateTime)});
                table1265.AddRow(new string[] {
                            "ChannelVersion",
                            "2"});
#line 432
 testRunner.And("there is a funding group version created in the release management repository", ((string)(null)), table1265, "And ");
#line hidden
#line 452
 testRunner.And("there are a total of \'9\' funding group version records created in the release man" +
                        "agement repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1266 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1266.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000001"});
                table1266.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000007"});
                table1266.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
#line 454
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1266, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1267 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1267.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000002"});
                table1267.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000007"});
                table1267.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
#line 459
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1267, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1268 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1268.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000003"});
                table1268.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000008"});
                table1268.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
#line 464
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1268, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1269 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1269.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000004"});
                table1269.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000008"});
                table1269.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
#line 469
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1269, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1270 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1270.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000005"});
                table1270.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000009"});
                table1270.AddRow(new string[] {
                            "VariationReason",
                            "FundingUpdated"});
#line 474
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1270, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1271 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1271.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000006"});
                table1271.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000009"});
                table1271.AddRow(new string[] {
                            "VariationReason",
                            "ProfilingUpdated"});
#line 479
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1271, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1272 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1272.AddRow(new string[] {
                            "FundingGroupVersionVariationReasonId",
                            "00000000-0000-0000-0000-000000000007"});
                table1272.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000009"});
                table1272.AddRow(new string[] {
                            "VariationReason",
                            "CalculationValuesUpdated"});
#line 484
 testRunner.And("there is a funding group variation reason created in the release management repos" +
                        "itory", ((string)(null)), table1272, "And ");
#line hidden
#line 489
 testRunner.And("there are a total of \'7\' funding group version variation reason records created i" +
                        "n the release management repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1273 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1273.AddRow(new string[] {
                            "FundingGroupProviderId",
                            "00000000-0000-0000-0000-000000000007"});
                table1273.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000007"});
                table1273.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000005"});
#line 491
 testRunner.And("there is the provider version associated with the funding group version in the re" +
                        "lease management repository", ((string)(null)), table1273, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1274 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1274.AddRow(new string[] {
                            "FundingGroupProviderId",
                            "00000000-0000-0000-0000-000000000008"});
                table1274.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000008"});
                table1274.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000005"});
#line 496
 testRunner.And("there is the provider version associated with the funding group version in the re" +
                        "lease management repository", ((string)(null)), table1274, "And ");
#line hidden
                TechTalk.SpecFlow.Table table1275 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1275.AddRow(new string[] {
                            "FundingGroupProviderId",
                            "00000000-0000-0000-0000-000000000009"});
                table1275.AddRow(new string[] {
                            "FundingGroupVersionId",
                            "00000000-0000-0000-0000-000000000009"});
                table1275.AddRow(new string[] {
                            "ReleasedProviderVersionChannelId",
                            "00000000-0000-0000-0000-000000000006"});
#line 501
 testRunner.And("there is the provider version associated with the funding group version in the re" +
                        "lease management repository", ((string)(null)), table1275, "And ");
#line hidden
#line 506
 testRunner.And("there are a total of \'9\' funding group providers created in the release managemen" +
                        "t repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 508
 testRunner.And("there is content blob created for the funding group with ID \'PSG-AY-2122-Informat" +
                        "ion-LocalAuthority-212-3_0\' in the channel \'Statement\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 509
 testRunner.And("there is content blob created for the funding group with ID \'PSG-AY-2122-Payment-" +
                        "LocalAuthority-10004002-3_0\' in the channel \'Statement\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 510
 testRunner.And("there is content blob created for the funding group with ID \'PSG-AY-2122-Payment-" +
                        "LocalAuthority-10004002-3_0\' in the channel \'Payment\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 511
 testRunner.And("there are \'3\' files contained in the funding groups blob storage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 513
 testRunner.And("there is content blob created for the released published provider with ID \'PSG-AY" +
                        "-2122-10071690-3_0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 514
 testRunner.And("there are \'1\' files contained in the published providers blob storage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 516
 testRunner.And("there is content blob created for the released provider with ID \'PSG-AY-2122-1007" +
                        "1690-3_0\' in channel \'Payment\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 517
 testRunner.And("there is content blob created for the released provider with ID \'PSG-AY-2122-1007" +
                        "1690-3_0\' in channel \'Statement\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 518
 testRunner.And("there are \'2\' files contained in the released providers blob storage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Release a new major version of a provider which has already been released in two " +
            "channels: PSG")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ReleaseManagement-Subsequent release - multiple channels")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("releasemanagement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "PSG")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FundingStreamId", "PSG")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FundingPeriodId", "AY-2122")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SpecificationId", "3812005f-13b3-4d00-a118-d6cb0e2b2402")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Specification Name", "PE and Sport Grant")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProviderVersionId", "PSG-2021-10-11-78")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ProviderSnapshotId", "78")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CurrentDateTime", "2022-02-10 14:18:00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AuthorId", "AuthId")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AuthorName", "Author Name")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:CorrelationId", "Corr")]
        public virtual void ReleaseANewMajorVersionOfAProviderWhichHasAlreadyBeenReleasedInTwoChannels_PSG()
        {
#line 6
this.ReleaseANewMajorVersionOfAProviderWhichHasAlreadyBeenReleasedInTwoChannels("PSG", "AY-2122", "3812005f-13b3-4d00-a118-d6cb0e2b2402", "PE and Sport Grant", "PSG-2021-10-11-78", "78", "2022-02-10 14:18:00", "AuthId", "Author Name", "Corr", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
