<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CalculateFunding.Services.Policy</RootNamespace>
    <DebugType>full</DebugType>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    
    
    <PackageReference Include="CalculateFunding.Common.ApiClient.Calcs" Version="10.0.0" />
    <PackageReference Include="CalculateFunding.Common.ApiClient.fds" Version="2.0.2" />
    <PackageReference Include="CalculateFunding.Common.ApiClient.Policies" Version="9.0.3" />
    <PackageReference Include="CalculateFunding.Common.ApiClient.Results" Version="8.0.0" />
    <PackageReference Include="CalculateFunding.Common.ApiClient.Specifications" Version="8.0.0" />
    <PackageReference Include="CalculateFunding.Common.Config.ApiClient.Results" Version="7.0.0" />
    <PackageReference Include="CalculateFunding.Common.JobManagement" Version="9.0.0" />
    <PackageReference Include="CalculateFunding.Common.Storage" Version="4.0.0" />
    <PackageReference Include="CalculateFunding.Common.TemplateMetadata.Schema10" Version="4.0.0" />
    <PackageReference Include="CalculateFunding.Common.TemplateMetadata.Schema11" Version="4.0.0" />
    <PackageReference Include="CalculateFunding.Common.TemplateMetadata.Schema12" Version="3.0.2" />
    <PackageReference Include="FluentValidation" Version="8.6.2" />
    
    
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NJsonSchema" Version="10.6.6" />
    
    <PackageReference Include="YamlDotNet" Version="6.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CalculateFunding.Models.Policy\CalculateFunding.Models.Policy.csproj" />
    <ProjectReference Include="..\CalculateFunding.Repositories.Common.EFCore\CalculateFunding.Repositories.Common.EFCore.csproj" />
    <ProjectReference Include="..\CalculateFunding.Services.Core\CalculateFunding.Services.Core.csproj" />
    <ProjectReference Include="..\CalculateFunding.Services.Processing\CalculateFunding.Services.Processing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="MappingProfiles\" />
  </ItemGroup>
</Project>

