<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    
    
    <PackageReference Include="CalculateFunding.Common.Sql" Version="5.0.3" />
    
    
    
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CalculateFunding.Services.Core\CalculateFunding.Services.Core.csproj" />
  </ItemGroup>
</Project>

