<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <DebugType>full</DebugType>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    
    
    <PackageReference Include="CalculateFunding.Common.ApiClient.Jobs" Version="7.0.0" />
    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.10.0" />
    
    
    
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CalculateFunding.Models.CosmosDbScaling\CalculateFunding.Models.CosmosDbScaling.csproj" />
    <ProjectReference Include="..\CalculateFunding.Services.Core\CalculateFunding.Services.Core.csproj" />
    <ProjectReference Include="..\CalculateFunding.Services.Processing\CalculateFunding.Services.Processing.csproj" />
  </ItemGroup>
</Project>

