<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    
    
    <PackageReference Include="CalculateFunding.Common.ApiClient.FDS" Version="2.0.2" />
    <PackageReference Include="CalculateFunding.Common.Sql" Version="5.0.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.41" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SignalRService" Version="1.7.0" />
    
    
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CalculateFunding.Models.FundingDataZone\CalculateFunding.Models.FundingDataZone.csproj" />
    <ProjectReference Include="..\CalculateFunding.Services.Core\CalculateFunding.Services.Core.csproj" />
  </ItemGroup>
</Project>

