---
name: Build and Publish for Main and Release branches

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:

  audit-containers:
    name: Audit - Containers
    uses: DFE-Digital/funding-service-workflows/.github/workflows/audit-container-trivy.yml@9fdf8fb5087ede6e1ef9eebcae72e87d78e6721c
    with:
      dockerfilePath: CalculateFunding.Api.Calcs/Dockerfile

  build:
    name: Build and Publish
    needs: [audit-containers]
    uses: DFE-Digital/funding-service-workflows/.github/workflows/build-and-publish.yml@9fdf8fb5087ede6e1ef9eebcae72e87d78e6721c
    with:
      dockerfilePath: CalculateFunding.Api.Calcs/Dockerfile