<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <LangVersion>12.0</LangVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
    <FileVersion>1.0.0.$(VersionSuffix)</FileVersion>
	<OutputType>Exe</OutputType>
	<ImplicitUsings>enable</ImplicitUsings>
	<DockerFastModeProjectMountDirectory>/home/site/wwwroot</DockerFastModeProjectMountDirectory>
	<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
    <ItemGroup>
	    <PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="CalculateFunding.Common.Config.ApiClient.Datasets" Version="7.0.0" />
		<PackageReference Include="CalculateFunding.Common.Config.ApiClient.Jobs" Version="6.0.0" />
		<PackageReference Include="CalculateFunding.Common.Config.ApiClient.Policies" Version="6.0.0" />
		<PackageReference Include="CalculateFunding.Common.Config.ApiClient.Results" Version="7.0.0" />
	    <PackageReference Include="FluentValidation" Version="8.6.0" />
	    <PackageReference Include="Microsoft.CodeAnalysis" Version="3.6.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.22.2" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.3.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.18.1" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.24.0" />
	    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.6.0" />
	    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="3.6.0" />
	    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CalculateFunding.Services.CalcEngine\CalculateFunding.Services.CalcEngine.csproj" />
    <ProjectReference Include="..\CalculateFunding.Services.Calcs\CalculateFunding.Services.Calcs.csproj" />
    <ProjectReference Include="..\CalculateFunding.Services.Core.Functions\CalculateFunding.Services.Core.Functions.csproj" />
    <ProjectReference Include="..\CalculateFunding.Services.Processing\CalculateFunding.Services.Processing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
	<Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>

