// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CalculateFunding.Publishing.AcceptanceTests.Features.Refresh
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class RefreshDsgVariationsWithSecondOccurrenceFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "RefreshDsgVariationsWithSecondOccurrence.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Refresh", "RefreshDsgVariationsWithSecondOccurrence", "\tIn order to refresh funding for DSG\r\n\tAs a funding approver\r\n\tI want to refresh " +
                    "funding for all approved providers within a specification\r\n\tAnd for variations w" +
                    "ith the allocations to be taken into account", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "RefreshDsgVariationsWithSecondOccurrence")))
            {
                global::CalculateFunding.Publishing.AcceptanceTests.Features.Refresh.RefreshDsgVariationsWithSecondOccurrenceFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
            TechTalk.SpecFlow.Table table917 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table917.AddRow(new string[] {
                        "DefaultTemplateVersion",
                        "1.0"});
#line 8
 testRunner.Given("a funding configuration exists for funding stream \'DSG\' in funding period \'FY-202" +
                    "1\'", ((string)(null)), table917, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table918 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table918.AddRow(new string[] {
                        "GroupTypeIdentifier",
                        "UKPRN"});
            table918.AddRow(new string[] {
                        "GroupingReason",
                        "Payment"});
            table918.AddRow(new string[] {
                        "GroupTypeClassification",
                        "LegalEntity"});
            table918.AddRow(new string[] {
                        "OrganisationGroupTypeCode",
                        "LocalAuthority"});
#line 11
 testRunner.And("the funding configuration has the following organisation group", ((string)(null)), table918, "And ");
#line hidden
#line 17
 testRunner.And("the funding configuration is available in the policies repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table919 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table919.AddRow(new string[] {
                        "GroupTypeIdentifier",
                        "LACode"});
            table919.AddRow(new string[] {
                        "GroupingReason",
                        "Information"});
            table919.AddRow(new string[] {
                        "GroupTypeClassification",
                        "GeographicalBoundary"});
            table919.AddRow(new string[] {
                        "OrganisationGroupTypeCode",
                        "LocalAuthority"});
#line 18
 testRunner.And("the funding configuration has the following organisation group", ((string)(null)), table919, "And ");
#line hidden
#line 24
 testRunner.And("the funding configuration is available in the policies repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table920 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table920.AddRow(new string[] {
                        "GroupTypeIdentifier",
                        "LocalAuthorityClassificationTypeCode"});
            table920.AddRow(new string[] {
                        "GroupingReason",
                        "Information"});
            table920.AddRow(new string[] {
                        "GroupTypeClassification",
                        "GeographicalBoundary"});
            table920.AddRow(new string[] {
                        "OrganisationGroupTypeCode",
                        "LocalGovernmentGroup"});
#line 25
 testRunner.And("the funding configuration has the following organisation group", ((string)(null)), table920, "And ");
#line hidden
#line 31
 testRunner.And("the funding configuration is available in the policies repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table921 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table921.AddRow(new string[] {
                        "GroupTypeIdentifier",
                        "GovernmentOfficeRegionCode"});
            table921.AddRow(new string[] {
                        "GroupingReason",
                        "Information"});
            table921.AddRow(new string[] {
                        "GroupTypeClassification",
                        "GeographicalBoundary"});
            table921.AddRow(new string[] {
                        "OrganisationGroupTypeCode",
                        "GovernmentOfficeRegion"});
#line 32
 testRunner.And("the funding configuration has the following organisation group", ((string)(null)), table921, "And ");
#line hidden
#line 38
 testRunner.And("the funding configuration is available in the policies repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table922 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table922.AddRow(new string[] {
                        "GroupTypeIdentifier",
                        "CountryCode"});
            table922.AddRow(new string[] {
                        "GroupingReason",
                        "Information"});
            table922.AddRow(new string[] {
                        "GroupTypeClassification",
                        "GeographicalBoundary"});
            table922.AddRow(new string[] {
                        "OrganisationGroupTypeCode",
                        "Country"});
#line 39
 testRunner.And("the funding configuration has the following organisation group", ((string)(null)), table922, "And ");
#line hidden
#line 45
 testRunner.And("the funding configuration is available in the policies repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table923 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table923.AddRow(new string[] {
                        "Id",
                        "FY-2021"});
            table923.AddRow(new string[] {
                        "Name",
                        "Financial Year 2020-21"});
            table923.AddRow(new string[] {
                        "StartDate",
                        "2019-08-01 00:00:00"});
            table923.AddRow(new string[] {
                        "EndDate",
                        "2020-07-31 00:00:00"});
            table923.AddRow(new string[] {
                        "Period",
                        "2021"});
            table923.AddRow(new string[] {
                        "Type",
                        "FY"});
#line 46
 testRunner.And("the funding period exists in the policies service", ((string)(null)), table923, "And ");
#line hidden
            TechTalk.SpecFlow.Table table924 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table924.AddRow(new string[] {
                        "Id",
                        "specForPublishing"});
            table924.AddRow(new string[] {
                        "Name",
                        "Test Specification for Publishing"});
            table924.AddRow(new string[] {
                        "IsSelectedForFunding",
                        "true"});
            table924.AddRow(new string[] {
                        "ProviderVersionId",
                        "dsg-providers-2.0"});
#line 54
 testRunner.And("the following specification exists", ((string)(null)), table924, "And ");
#line hidden
#line 60
 testRunner.And("the specification has the funding period with id \'FY-2021\' and name \'Financial Ye" +
                    "ar 2020-21\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table925 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Id"});
            table925.AddRow(new string[] {
                        "DSG",
                        "DSG"});
#line 61
 testRunner.And("the specification has the following funding streams", ((string)(null)), table925, "And ");
#line hidden
            TechTalk.SpecFlow.Table table926 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table926.AddRow(new string[] {
                        "DSG",
                        "1.0.Variations"});
#line 64
 testRunner.And("the specification has the following template versions for funding streams", ((string)(null)), table926, "And ");
#line hidden
#line 67
 testRunner.And("the specification is approved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table927 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table927.AddRow(new string[] {
                        "StatusChangedDate",
                        "2019-09-27 00:00:00"});
            table927.AddRow(new string[] {
                        "ExternalPublicationDate",
                        "2019-09-28 00:00:00"});
            table927.AddRow(new string[] {
                        "EarliestPaymentAvailableDate",
                        "2019-09-29 00:00:00"});
#line 68
 testRunner.And("the publishing dates for the specifcation are set as following", ((string)(null)), table927, "And ");
#line hidden
            TechTalk.SpecFlow.Table table928 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table928.AddRow(new string[] {
                        "JobDefinitionId",
                        "PublishFundingJob"});
            table928.AddRow(new string[] {
                        "InvokerUserId",
                        "PublishUserId"});
            table928.AddRow(new string[] {
                        "InvokerUserDisplayName",
                        "Invoker User"});
            table928.AddRow(new string[] {
                        "ParentJobId",
                        ""});
#line 73
 testRunner.And("the following job is requested to be queued for the current specification", ((string)(null)), table928, "And ");
#line hidden
#line 79
 testRunner.And("the job is submitted to the job service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table929 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table929.AddRow(new string[] {
                        "ProviderVersionId",
                        "dsg-providers-2.0"});
            table929.AddRow(new string[] {
                        "VersionType",
                        "Custom"});
            table929.AddRow(new string[] {
                        "Name",
                        "DSG Provider Version"});
            table929.AddRow(new string[] {
                        "Description",
                        "Acceptance Tests"});
            table929.AddRow(new string[] {
                        "Version",
                        "2"});
            table929.AddRow(new string[] {
                        "TargetDate",
                        "2019-12-12 00:00"});
            table929.AddRow(new string[] {
                        "FundingStream",
                        "DSG"});
            table929.AddRow(new string[] {
                        "Created",
                        "2019-12-11 00:00"});
#line 80
 testRunner.And("the following provider version exists in the providers service", ((string)(null)), table929, "And ");
#line hidden
            TechTalk.SpecFlow.Table table930 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table930.AddRow(new string[] {
                        "ProviderId",
                        "1000000"});
            table930.AddRow(new string[] {
                        "FundingStreamId",
                        "DSG"});
            table930.AddRow(new string[] {
                        "FundingPeriodId",
                        "FY-2021"});
            table930.AddRow(new string[] {
                        "TemplateVersion",
                        "1.0"});
            table930.AddRow(new string[] {
                        "Status",
                        "Released"});
            table930.AddRow(new string[] {
                        "TotalFunding",
                        "14000"});
            table930.AddRow(new string[] {
                        "MajorVersion",
                        "0"});
            table930.AddRow(new string[] {
                        "MinorVersion",
                        "1"});
#line 90
 testRunner.And("the following Published Provider has been previously generated for the current sp" +
                    "ecification", ((string)(null)), table930, "And ");
#line hidden
            TechTalk.SpecFlow.Table table931 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "FundingLineCode",
                        "Value",
                        "TemplateLineId",
                        "Type"});
            table931.AddRow(new string[] {
                        "Total DSG after deductions and recoupment",
                        "DSG-002",
                        "14000",
                        "3",
                        "Payment"});
#line 100
 testRunner.And("the Published Provider has the following funding lines", ((string)(null)), table931, "And ");
#line hidden
            TechTalk.SpecFlow.Table table932 = new TechTalk.SpecFlow.Table(new string[] {
                        "DistributionPeriodId",
                        "Value"});
            table932.AddRow(new string[] {
                        "FY-2021",
                        "14000"});
#line 103
 testRunner.And("the Published Provider has the following distribution period for funding line \'DS" +
                    "G-002\'", ((string)(null)), table932, "And ");
#line hidden
            TechTalk.SpecFlow.Table table933 = new TechTalk.SpecFlow.Table(new string[] {
                        "DistributionPeriodId",
                        "Type",
                        "TypeValue",
                        "Year",
                        "Occurrence",
                        "ProfiledValue"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "April",
                        "2021",
                        "1",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "April",
                        "2021",
                        "2",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "May",
                        "2021",
                        "1",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "May",
                        "2021",
                        "2",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "June",
                        "2021",
                        "1",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "June",
                        "2021",
                        "2",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "July",
                        "2021",
                        "1",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "July",
                        "2021",
                        "2",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "August",
                        "2021",
                        "1",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "August",
                        "2021",
                        "2",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "September",
                        "2021",
                        "1",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "September",
                        "2021",
                        "2",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "October",
                        "2021",
                        "1",
                        "2000"});
            table933.AddRow(new string[] {
                        "FY-2021",
                        "CalendarMonth",
                        "October",
                        "2021",
                        "2",
                        "2000"});
#line 106
 testRunner.And("the Published Providers distribution period has the following profiles for fundin" +
                    "g line \'DSG-002\'", ((string)(null)), table933, "And ");
#line hidden
            TechTalk.SpecFlow.Table table934 = new TechTalk.SpecFlow.Table(new string[] {
                        "EntityType",
                        "CalculationId",
                        "TemplateId",
                        "Name"});
            table934.AddRow(new string[] {
                        "Calculation",
                        "5cfb28de-88d6-4faa-a936-d81a065fb596",
                        "219",
                        "Stub for total funding"});
#line 122
 testRunner.And("template mapping exists", ((string)(null)), table934, "And ");
#line hidden
            TechTalk.SpecFlow.Table table935 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table935.AddRow(new string[] {
                        "ProviderId",
                        "1000000"});
            table935.AddRow(new string[] {
                        "Name",
                        "Maintained School 1"});
            table935.AddRow(new string[] {
                        "Authority",
                        "Local Authority 1"});
            table935.AddRow(new string[] {
                        "DateOpened",
                        "2012-03-15"});
            table935.AddRow(new string[] {
                        "LACode",
                        "200"});
            table935.AddRow(new string[] {
                        "LocalAuthorityName",
                        "Maintained School 1"});
            table935.AddRow(new string[] {
                        "ProviderType",
                        "LA maintained schools"});
            table935.AddRow(new string[] {
                        "ProviderSubType",
                        "Community school"});
            table935.AddRow(new string[] {
                        "ProviderVersionId",
                        "dsg-providers-2.0"});
            table935.AddRow(new string[] {
                        "TrustStatus",
                        "Not Supported By A Trust"});
            table935.AddRow(new string[] {
                        "UKPRN",
                        "1000000"});
#line 125
 testRunner.And("the Published Provider has the following provider information", ((string)(null)), table935, "And ");
#line hidden
#line 138
 testRunner.And("the Published Provider is available in the repository for this specification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table936 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table936.AddRow(new string[] {
                        "ProviderId",
                        "1000000"});
            table936.AddRow(new string[] {
                        "Name",
                        "Maintained School 1 - Changed"});
            table936.AddRow(new string[] {
                        "Authority",
                        "Local Authority 1"});
            table936.AddRow(new string[] {
                        "DateOpened",
                        "2012-03-15"});
            table936.AddRow(new string[] {
                        "LACode",
                        "200"});
            table936.AddRow(new string[] {
                        "LocalAuthorityName",
                        "Maintained School 1"});
            table936.AddRow(new string[] {
                        "ProviderType",
                        "LA maintained schools"});
            table936.AddRow(new string[] {
                        "ProviderSubType",
                        "Community school"});
            table936.AddRow(new string[] {
                        "ProviderVersionId",
                        "dsg-providers-2.0"});
            table936.AddRow(new string[] {
                        "TrustStatus",
                        "Not Supported By A Trust"});
            table936.AddRow(new string[] {
                        "UKPRN",
                        "1000000"});
#line 139
 testRunner.And("the following provider exists within core provider data in provider version \'dsg-" +
                    "providers-2.0\'", ((string)(null)), table936, "And ");
#line hidden
#line 152
 testRunner.And("the provider with id \'1000000\' should be a scoped provider in the current specifi" +
                    "cation in provider version \'dsg-providers-2.0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table937 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table937.AddRow(new string[] {
                        "ProviderId",
                        "9000000"});
            table937.AddRow(new string[] {
                        "Name",
                        "Local Authority 1"});
            table937.AddRow(new string[] {
                        "Authority",
                        "Local Authority 1"});
            table937.AddRow(new string[] {
                        "DateOpened",
                        "2012-03-15"});
            table937.AddRow(new string[] {
                        "LACode",
                        "200"});
            table937.AddRow(new string[] {
                        "LocalAuthorityName",
                        "Local Authority 1"});
            table937.AddRow(new string[] {
                        "ProviderType",
                        "Local Authority"});
            table937.AddRow(new string[] {
                        "ProviderSubType",
                        "Local Authority"});
            table937.AddRow(new string[] {
                        "ProviderVersionId",
                        "<ProviderVersionId>"});
            table937.AddRow(new string[] {
                        "TrustStatus",
                        "Not Supported By A Trust"});
            table937.AddRow(new string[] {
                        "UKPRN",
                        "9000000"});
#line 154
 testRunner.And("the following provider exists within core provider data in provider version \'dsg-" +
                    "providers-2.0\'", ((string)(null)), table937, "And ");
#line hidden
            TechTalk.SpecFlow.Table table938 = new TechTalk.SpecFlow.Table(new string[] {
                        "CalculationType",
                        "CalculationId",
                        "Name",
                        "PublishStatus"});
            table938.AddRow(new string[] {
                        "Template",
                        "5cfb28de-88d6-4faa-a936-d81a065fb596",
                        "Stub for total funding",
                        "Approved"});
#line 167
 testRunner.And("calculation meta data exists for \'DSG\'", ((string)(null)), table938, "And ");
#line hidden
#line 170
 testRunner.And("variations are enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table939 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Order"});
            table939.AddRow(new string[] {
                        "ProviderMetadata",
                        "0"});
            table939.AddRow(new string[] {
                        "DsgTotalAllocationChange",
                        "1"});
            table939.AddRow(new string[] {
                        "FundingUpdated",
                        "2"});
            table939.AddRow(new string[] {
                        "ProfilingUpdated",
                        "3"});
            table939.AddRow(new string[] {
                        "PupilNumberSuccessor",
                        "4"});
#line 171
 testRunner.And("the funding configuration has the following funding variations", ((string)(null)), table939, "And ");
#line hidden
            TechTalk.SpecFlow.Table table940 = new TechTalk.SpecFlow.Table(new string[] {
                        "FundingLineId",
                        "FundingStreamId",
                        "FundingPeriodId"});
            table940.AddRow(new string[] {
                        "DSG-002",
                        "DSG",
                        "FY-2021"});
#line 178
 testRunner.And("the following profile pattern exists", ((string)(null)), table940, "And ");
#line hidden
        }
    }
}
#pragma warning restore
#endregion
