---
name: Build and Publish for Main and Release branches

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:

  audit-containers:
    name: Audit - Containers
    uses: DFE-Digital/funding-service-workflows/.github/workflows/audit-container-trivy.yml@9fdf8fb5087ede6e1ef9eebcae72e87d78e6721c
    with:
      dockerfilePath: api/Dockerfile

 
  build:
    name: Build and Publish
    uses: DFE-Digital/funding-service-workflows/.github/workflows/build-and-publish.yml@9fdf8fb5087ede6e1ef9eebcae72e87d78e6721c
    # needs: [audit-containers, audit-dependencies, lint-yaml]
    needs: [audit-containers]
    with:
      dockerfilePath: api/Dockerfile
